/* Master Formula Vault - extracted from Chapter 49.
   Generated by tools/extract_data.py - do not edit by hand. */
const FORMULAS = [
  {
    "paper": "MA",
    "title": "Contribution per unit",
    "eq": "Selling Price − Variable Cost per unit",
    "section": "Ch5 — Core Formulas"
  },
  {
    "paper": "MA",
    "title": "Break-Even Point (units)",
    "eq": "Fixed Costs ÷ Contribution per unit",
    "section": "Ch5 — Core Formulas"
  },
  {
    "paper": "MA",
    "title": "Break-Even Revenue ($)",
    "eq": "Fixed Costs ÷ Contribution to Sales Ratio",
    "section": "Ch5 — Core Formulas"
  },
  {
    "paper": "MA",
    "title": "Contribution to Sales Ratio (C/S Ratio)",
    "eq": "(Contribution ÷ Revenue) × 100",
    "section": "Ch5 — Core Formulas"
  },
  {
    "paper": "MA",
    "title": "Margin of Safety",
    "eq": "Actual Sales − Break-Even Sales",
    "section": "Ch5 — Core Formulas"
  },
  {
    "paper": "MA",
    "title": "Marginal Costing Profit",
    "eq": "Contribution − Fixed Costs",
    "section": "Ch5 — Core Formulas"
  },
  {
    "paper": "MA",
    "title": "Material Price Variance",
    "eq": "(Standard Price − Actual Price) × Actual Quantity",
    "section": "Ch6 — Core Variance Formulas"
  },
  {
    "paper": "MA",
    "title": "Material Usage Variance",
    "eq": "(Standard Qty − Actual Qty) × Standard Price",
    "section": "Ch6 — Core Variance Formulas"
  },
  {
    "paper": "MA",
    "title": "Labour Rate Variance",
    "eq": "(Standard Rate − Actual Rate) × Actual Hours",
    "section": "Ch6 — Core Variance Formulas"
  },
  {
    "paper": "MA",
    "title": "Labour Efficiency Variance",
    "eq": "(Standard Hours − Actual Hours) × Standard Rate",
    "section": "Ch6 — Core Variance Formulas"
  },
  {
    "paper": "MA",
    "title": "Sales Price Variance",
    "eq": "(Actual Price − Standard Price) × Actual Volume",
    "section": "Ch6 — Core Variance Formulas"
  },
  {
    "paper": "MA",
    "title": "Sales Volume Variance",
    "eq": "(Actual Volume − Budgeted Volume) × Standard Margin",
    "section": "Ch6 — Core Variance Formulas"
  },
  {
    "paper": "FA / FR",
    "title": "Accounting Equation",
    "eq": "Assets = Liabilities + Equity",
    "section": "Ch2 — Core Formulas"
  },
  {
    "paper": "FA / FR",
    "title": "Expanded Equation",
    "eq": "Assets = Liabilities + Capital + Income − Expenses − Drawings",
    "section": "Ch2 — Core Formulas"
  },
  {
    "paper": "FA / FR",
    "title": "Trial Balance Check",
    "eq": "Total Debits = Total Credits",
    "section": "Ch2 — Core Formulas"
  },
  {
    "paper": "FR",
    "title": "Price Allocation to an Obligation",
    "eq": "(SSP of Obligation ÷ Total SSP of All Obligations) × Total Transaction Price",
    "section": "Ch7 — Core Formula"
  },
  {
    "paper": "FR",
    "title": "Lease Liability (Initial)",
    "eq": "Present Value of Future Lease Payments, discounted at the interest rate implicit in the lease (or the lessee's incremental borrowing rate if that rate isn't readily determinable)",
    "section": "Ch8 — IFRS 16 — Initial Recognition"
  },
  {
    "paper": "FR",
    "title": "Right-of-Use (ROU) Asset (Initial)",
    "eq": "Lease Liability + Initial Direct Costs + Payments Made Before Commencement − Lease Incentives Received",
    "section": "Ch8 — IFRS 16 — Initial Recognition"
  },
  {
    "paper": "FR",
    "title": "Subsequent Measurement — Liability",
    "eq": "Increases by interest charged (unwinding the discount) each period, decreases by actual lease payments made — same logic as a loan amortisation schedule",
    "section": "Ch8 — IFRS 16 — Initial Recognition"
  },
  {
    "paper": "FR",
    "title": "Subsequent Measurement — ROU Asset",
    "eq": "Depreciated on a straight-line basis (usually) over the shorter of the lease term or the asset's useful life",
    "section": "Ch8 — IFRS 16 — Initial Recognition"
  },
  {
    "paper": "FR",
    "title": "Depreciable Amount",
    "eq": "Cost (or Revalued Amount) − Residual Value",
    "section": "Ch8 — Core Formulas"
  },
  {
    "paper": "FR",
    "title": "Straight-Line Depreciation",
    "eq": "(Cost − Residual Value) ÷ Useful Life",
    "section": "Ch8 — Core Formulas"
  },
  {
    "paper": "FR",
    "title": "Reducing Balance Depreciation",
    "eq": "Carrying Amount × Depreciation Rate %",
    "section": "Ch8 — Core Formulas"
  },
  {
    "paper": "FR",
    "title": "Units of Production Depreciation",
    "eq": "(Cost − Residual Value) ÷ Total Units × Units This Period",
    "section": "Ch8 — Core Formulas"
  },
  {
    "paper": "FR",
    "title": "Carrying Amount",
    "eq": "Cost − Accumulated Depreciation (− Impairment, if any)",
    "section": "Ch8 — Core Formulas"
  },
  {
    "paper": "FR",
    "title": "Revaluation Surplus/Deficit",
    "eq": "Fair Value − Carrying Amount (before revaluation)",
    "section": "Ch8 — Core Formulas"
  },
  {
    "paper": "FR",
    "title": "Inventory Valuation Rule",
    "eq": "Lower of Cost and Net Realisable Value (NRV)",
    "section": "Ch9 — Core Formulas"
  },
  {
    "paper": "FR",
    "title": "Net Realisable Value",
    "eq": "Estimated Selling Price − Costs of Completion − Selling Costs",
    "section": "Ch9 — Core Formulas"
  },
  {
    "paper": "FR",
    "title": "Weighted Average Cost (recalculated)",
    "eq": "Total Value of Inventory ÷ Total Units Held",
    "section": "Ch9 — Core Formulas"
  },
  {
    "paper": "FR",
    "title": "Inventory Write-Down",
    "eq": "(Cost − NRV) × Units Affected",
    "section": "Ch9 — Core Formulas"
  },
  {
    "paper": "FR / SBR",
    "title": "Expected Credit Loss (ECL)",
    "eq": "Probability of Default × Loss Given Default × Exposure at Default",
    "section": "Ch10 — Core Formulas"
  },
  {
    "paper": "FR / SBR",
    "title": "Amortised Cost Interest Income",
    "eq": "Opening Carrying Amount × Effective Interest Rate",
    "section": "Ch10 — Core Formulas"
  },
  {
    "paper": "FR / SBR",
    "title": "Compound Instrument — Equity Component",
    "eq": "Total Proceeds − Liability Component (PV at market rate)",
    "section": "Ch10 — Core Formulas"
  },
  {
    "paper": "FR / SBR",
    "title": "FVTPL Gain/Loss",
    "eq": "Fair Value at Reporting Date − Carrying Amount",
    "section": "Ch10 — Core Formulas"
  },
  {
    "paper": "FR / SBR",
    "title": "Goodwill",
    "eq": "Consideration Paid + Fair Value of NCI − Fair Value of Identifiable Net Assets",
    "section": "Ch11 — Core Formulas"
  },
  {
    "paper": "FR / SBR",
    "title": "NCI at Acquisition (Proportionate Method)",
    "eq": "NCI % × Fair Value of Identifiable Net Assets",
    "section": "Ch11 — Core Formulas"
  },
  {
    "paper": "FR / SBR",
    "title": "Group Retained Earnings",
    "eq": "Parent's RE + (Parent's % × Subsidiary's Post-Acquisition Profit) − PUP (Parent's share)",
    "section": "Ch11 — Core Formulas"
  },
  {
    "paper": "FR / SBR",
    "title": "Unrealised Profit in Inventory (PUP)",
    "eq": "Closing Inventory (at transfer price) × Profit Margin %",
    "section": "Ch11 — Core Formulas"
  },
  {
    "paper": "FR / SBR",
    "title": "Profit Attributable to NCI",
    "eq": "NCI % × Subsidiary's Adjusted Profit for the Year",
    "section": "Ch11 — Core Formulas"
  },
  {
    "paper": "FR",
    "title": "Basic EPS",
    "eq": "Profit Attributable to Ordinary Shareholders ÷ Weighted Average Number of Ordinary Shares Outstanding During the Period",
    "section": "Ch12 — EPS Formulas"
  },
  {
    "paper": "FR",
    "title": "Diluted EPS",
    "eq": "Adjusted Profit ÷ (Weighted Average Shares + All Potentially Dilutive Shares — from convertible bonds, share options, convertible preference shares)",
    "section": "Ch12 — EPS Formulas"
  },
  {
    "paper": "FR",
    "title": "Gross Profit Margin",
    "eq": "Gross Profit ÷ Revenue × 100",
    "section": "Ch12 — Complete Ratio Reference"
  },
  {
    "paper": "FR",
    "title": "ROCE",
    "eq": "Operating Profit ÷ Capital Employed × 100",
    "section": "Ch12 — Complete Ratio Reference"
  },
  {
    "paper": "FR",
    "title": "ROE",
    "eq": "Profit After Tax ÷ Shareholders' Equity × 100",
    "section": "Ch12 — Complete Ratio Reference"
  },
  {
    "paper": "FR",
    "title": "Current Ratio",
    "eq": "Current Assets ÷ Current Liabilities",
    "section": "Ch12 — Complete Ratio Reference"
  },
  {
    "paper": "FR",
    "title": "Quick Ratio",
    "eq": "(Current Assets − Inventory) ÷ Current Liabilities",
    "section": "Ch12 — Complete Ratio Reference"
  },
  {
    "paper": "FR",
    "title": "Cash Conversion Cycle",
    "eq": "Inventory Days + Receivables Days − Payables Days",
    "section": "Ch12 — Complete Ratio Reference"
  },
  {
    "paper": "FR",
    "title": "Gearing Ratio",
    "eq": "Total Debt ÷ Total Equity × 100",
    "section": "Ch12 — Complete Ratio Reference"
  },
  {
    "paper": "FR",
    "title": "Interest Cover",
    "eq": "EBIT ÷ Interest Expense",
    "section": "Ch12 — Complete Ratio Reference"
  },
  {
    "paper": "FR",
    "title": "EPS",
    "eq": "Profit Attributable to Ordinary Shareholders ÷ Weighted Avg No. of Shares",
    "section": "Ch12 — Complete Ratio Reference"
  },
  {
    "paper": "FR",
    "title": "P/E Ratio",
    "eq": "Share Price ÷ EPS",
    "section": "Ch12 — Complete Ratio Reference"
  },
  {
    "paper": "FR",
    "title": "Recoverable Amount",
    "eq": "Higher of Fair Value Less Costs of Disposal, and Value in Use — if Carrying Amount exceeds this, the asset is impaired and written down",
    "section": "Ch4 — IAS 36 Impairment"
  },
  {
    "paper": "LW",
    "title": "1. Offer",
    "eq": "A clear, definite statement of terms one party is willing to be bound by if accepted. Must be distinguished from an \"invitation to treat\" (e.g. goods displayed in a shop window are an invitation to treat, not an offer — the customer makes the offer at the till).",
    "section": "Ch23 — The 4 Essential Elements of a Valid Contract"
  },
  {
    "paper": "LW",
    "title": "2. Acceptance",
    "eq": "Unqualified agreement to all terms of the offer, communicated to the offeror. A \"counter-offer\" (changing any term) destroys the original offer and becomes a new offer itself.",
    "section": "Ch23 — The 4 Essential Elements of a Valid Contract"
  },
  {
    "paper": "LW",
    "title": "3. Consideration",
    "eq": "Something of value given by each party — the \"price\" of the promise. Must have SOME value (need not be adequate/fair value) and must NOT be past (a promise to pay for something already done is generally not valid consideration).",
    "section": "Ch23 — The 4 Essential Elements of a Valid Contract"
  },
  {
    "paper": "LW",
    "title": "4. Intention to Create Legal Relations",
    "eq": "Both parties must intend the agreement to be legally binding. Commercial agreements are PRESUMED to have this intention; social/domestic agreements are PRESUMED NOT to — either presumption can be rebutted with evidence.",
    "section": "Ch23 — The 4 Essential Elements of a Valid Contract"
  },
  {
    "paper": "LW",
    "title": "Damages",
    "eq": "Monetary compensation to put the innocent party in the position they would have been in had the contract been performed. Must be caused by the breach and not too \"remote\" (unforeseeable). The innocent party has a duty to \"mitigate\" loss — cannot recover losses that reasonable steps could have avoided.",
    "section": "Ch23 — Available Remedies"
  },
  {
    "paper": "LW",
    "title": "Specific Performance",
    "eq": "A court order requiring the breaching party to actually perform the contract. Discretionary — granted mainly where damages are inadequate (e.g. sale of unique goods or land), not for personal service contracts.",
    "section": "Ch23 — Available Remedies"
  },
  {
    "paper": "LW",
    "title": "Injunction",
    "eq": "A court order preventing a party from doing something that would breach the contract (e.g. preventing breach of a non-compete clause).",
    "section": "Ch23 — Available Remedies"
  },
  {
    "paper": "LW",
    "title": "Rescission",
    "eq": "Cancels the contract, putting parties back in their pre-contract position — typically the remedy for misrepresentation rather than breach.",
    "section": "Ch23 — Available Remedies"
  },
  {
    "paper": "PM",
    "title": "Throughput per Unit",
    "eq": "Selling Price − Direct Material Cost per Unit",
    "section": "Ch24 — Throughput Accounting Formulas"
  },
  {
    "paper": "PM",
    "title": "Throughput per Bottleneck Minute",
    "eq": "Throughput per Unit ÷ Bottleneck Minutes Required per Unit",
    "section": "Ch24 — Throughput Accounting Formulas"
  },
  {
    "paper": "PM",
    "title": "Total Factory Cost per Bottleneck Minute",
    "eq": "Total Factory Costs (Labour + Overheads) ÷ Total Bottleneck Minutes Available",
    "section": "Ch24 — Throughput Accounting Formulas"
  },
  {
    "paper": "PM",
    "title": "Throughput Accounting Ratio (TPAR)",
    "eq": "Throughput per Bottleneck Minute ÷ Factory Cost per Bottleneck Minute",
    "section": "Ch24 — Throughput Accounting Formulas"
  },
  {
    "paper": "PM",
    "title": "Cumulative Average Time Formula",
    "eq": "Y = a × X^b, where Y = cumulative average time per unit; a = time for the first unit; X = cumulative number of units produced; b = log(learning rate) ÷ log(2)",
    "section": "Ch24 — Learning Curve Formula"
  },
  {
    "paper": "PM",
    "title": "For an 80% Learning Curve",
    "eq": "b = log(0.8) ÷ log(2) = −0.3219",
    "section": "Ch24 — Learning Curve Formula"
  },
  {
    "paper": "PM",
    "title": "Total Time for X Units",
    "eq": "Cumulative Average Time (Y) × X (total units)",
    "section": "Ch24 — Learning Curve Formula"
  },
  {
    "paper": "PM",
    "title": "Incremental Time for a New Batch",
    "eq": "Total Time for New Cumulative Total − Total Time for Previous Cumulative Total",
    "section": "Ch24 — Learning Curve Formula"
  },
  {
    "paper": "PM",
    "title": "Material Mix Variance",
    "eq": "(Actual Total Quantity in Standard Mix Proportion − Actual Quantity Used) × Standard Price, for each material — summed",
    "section": "Ch24 — Mix & Yield Variance Formulas"
  },
  {
    "paper": "PM",
    "title": "Material Yield Variance",
    "eq": "(Standard Output-Based Input Quantity − Actual Total Input Quantity Used, in standard mix proportions) × Standard Weighted Average Cost per unit of input",
    "section": "Ch24 — Mix & Yield Variance Formulas"
  },
  {
    "paper": "PM",
    "title": "Check",
    "eq": "Mix Variance + Yield Variance = Total Material Usage Variance",
    "section": "Ch24 — Mix & Yield Variance Formulas"
  },
  {
    "paper": "FM",
    "title": "Sales Budget",
    "eq": "Expected Units Sold × Selling Price = Budgeted Revenue — the starting point of the entire budget process",
    "section": "Ch20 — Budgeting Formulas (FP&A)"
  },
  {
    "paper": "FM",
    "title": "Production Budget (units)",
    "eq": "Sales Units + Closing Inventory Target − Opening Inventory",
    "section": "Ch20 — Budgeting Formulas (FP&A)"
  },
  {
    "paper": "FM",
    "title": "Direct Materials Budget",
    "eq": "Materials Needed for Planned Production × Standard Cost per Unit of Material",
    "section": "Ch20 — Budgeting Formulas (FP&A)"
  },
  {
    "paper": "FM",
    "title": "Direct Labour Budget",
    "eq": "Standard Labour Hours per Unit × Planned Production × Wage Rate per Hour",
    "section": "Ch20 — Budgeting Formulas (FP&A)"
  },
  {
    "paper": "TX",
    "title": "Domestic Company (General Rate)",
    "eq": "30% + Surcharge + Health & Education Cess 4% Surcharge: 7% if income ₹1–10Cr; 12% if income above ₹10Cr Effective rate for large companies: ~34.94%",
    "section": "Ch37 — Corporate Tax Rates — India (AY 2024-25)"
  },
  {
    "paper": "TX",
    "title": "Concessional Rate — Section 115BAA",
    "eq": "22% + Surcharge 10% + Cess 4% = Effective ~25.17% Available to all existing domestic companies — cannot claim certain deductions (80IC, 80IE etc.). Most large companies have opted for this. Announced in September 2019 — major corporate tax cut.",
    "section": "Ch37 — Corporate Tax Rates — India (AY 2024-25)"
  },
  {
    "paper": "TX",
    "title": "New Manufacturing Companies — Section 115BAB",
    "eq": "15% + Surcharge 10% + Cess 4% = Effective ~17.16% For new domestic manufacturing companies incorporated after 1 Oct 2019 and commencing production before 31 Mar 2024 (extended). India's lowest corporate tax rate — designed to attract manufacturing investment (Make in India). Cannot claim most deductions.",
    "section": "Ch37 — Corporate Tax Rates — India (AY 2024-25)"
  },
  {
    "paper": "TX",
    "title": "Foreign Companies",
    "eq": "40% + Surcharge + Cess 4% On income arising in India. May be reduced by DTAA (Double Tax Avoidance Agreements) with the country of the foreign company's residence.",
    "section": "Ch37 — Corporate Tax Rates — India (AY 2024-25)"
  },
  {
    "paper": "TX",
    "title": "Minimum Alternate Tax (MAT)",
    "eq": "15% of Book Profit (if tax payable under normal provisions is less) Ensures companies with high book profits but low taxable income (due to deductions) still pay minimum tax. MAT credit can be carried forward 15 years. Companies opting for 115BAA/BAB are exempt from MAT.",
    "section": "Ch37 — Corporate Tax Rates — India (AY 2024-25)"
  },
  {
    "paper": "TX",
    "title": "Temporary Difference",
    "eq": "Carrying Amount (per IFRS balance sheet) − Tax Base (per tax rules) Carrying amount = IFRS book value of asset or liability. Tax base = amount attributed to asset/liability for tax purposes (i.e. what tax law says it's worth).",
    "section": "Ch37 — Deferred Tax — Core Concepts"
  },
  {
    "paper": "TX",
    "title": "Deferred Tax Liability (DTL)",
    "eq": "When carrying amount of ASSET > tax base → TAXABLE temporary difference → DTL Will result in more tax in the future. Example: Accelerated tax depreciation — asset depreciated faster for tax than for accounting. Book value > tax base → DTL recognised.",
    "section": "Ch37 — Deferred Tax — Core Concepts"
  },
  {
    "paper": "TX",
    "title": "Deferred Tax Asset (DTA)",
    "eq": "When carrying amount of ASSET < tax base → DEDUCTIBLE temporary difference → DTA Will result in less tax in the future. Example: Provision for bad debts — not deductible until debt actually written off. Provision reduces book value of receivable below tax base → DTA. Also: tax losses carried forward → DTA (if probable future profits to use them against).",
    "section": "Ch37 — Deferred Tax — Core Concepts"
  },
  {
    "paper": "TX",
    "title": "Deferred Tax Calculation",
    "eq": "Deferred Tax = Temporary Difference × Applicable Tax Rate Use the tax rate expected to apply when the difference reverses — typically the enacted or substantively enacted future tax rate, not current year's rate.",
    "section": "Ch37 — Deferred Tax — Core Concepts"
  },
  {
    "paper": "TX",
    "title": "Tax Expense in P&L (IAS 12)",
    "eq": "Tax Expense = Current Tax + Deferred Tax Expense (or − Deferred Tax Income) Current Tax = Tax payable on this year's taxable profit per tax return. Deferred Tax = Change in deferred tax liability/asset during the year. Both components separately disclosed in notes.",
    "section": "Ch37 — Tax in the P&L and Balance Sheet — Full Picture"
  },
  {
    "paper": "TX",
    "title": "Current Tax",
    "eq": "Taxable Profit × Current Tax Rate Taxable profit ≠ accounting profit. Adjust for: disallowed expenses (add back), non-taxable income (deduct), timing differences. Recognised as a liability (tax payable) until paid.",
    "section": "Ch37 — Tax in the P&L and Balance Sheet — Full Picture"
  },
  {
    "paper": "TX",
    "title": "Effective Tax Rate",
    "eq": "Tax Expense ÷ Profit Before Tax × 100% Shows the true % of accounting profit paid as tax. Differs from statutory rate due to: deferred tax, permanent differences (exempt income, disallowed expenses), prior year adjustments. Important metric for financial analysis — compare to statutory rate to understand tax efficiency.",
    "section": "Ch37 — Tax in the P&L and Balance Sheet — Full Picture"
  },
  {
    "paper": "TX",
    "title": "Balance Sheet Presentation",
    "eq": "Current Tax Liability: tax payable for current and prior years (current liability) Deferred Tax Liability: non-current liability (usually) Deferred Tax Asset: non-current asset (if recognition criteria met) DTA and DTL for same tax jurisdiction may be offset if legally enforceable right to offset exists.",
    "section": "Ch37 — Tax in the P&L and Balance Sheet — Full Picture"
  },
  {
    "paper": "TX",
    "title": "Deferred Tax",
    "eq": "DT = (Carrying Amount − Tax Base) × Future Tax Rate | Positive = DTL | Negative = DTA",
    "section": "Ch37 — Key Formulas & Rates"
  },
  {
    "paper": "TX",
    "title": "Effective Tax Rate",
    "eq": "ETR = Tax Expense ÷ Profit Before Tax × 100%",
    "section": "Ch37 — Key Formulas & Rates"
  },
  {
    "paper": "TX",
    "title": "Interest Tax Shield",
    "eq": "Tax Shield = Interest Paid × Tax Rate | After-tax cost of debt = Kd × (1 − tax rate)",
    "section": "Ch37 — Key Formulas & Rates"
  },
  {
    "paper": "TX",
    "title": "GST Payable",
    "eq": "GST Payable = Output Tax (on sales) − Input Tax Credit (on purchases)",
    "section": "Ch37 — Key Formulas & Rates"
  },
  {
    "paper": "TX",
    "title": "Advance Tax Schedule",
    "eq": "15% by 15 June | 45% by 15 Sep | 75% by 15 Dec | 100% by 15 Mar",
    "section": "Ch37 — Key Formulas & Rates"
  },
  {
    "paper": "TX",
    "title": "Section 115BAA Rate",
    "eq": "22% + 10% surcharge + 4% cess = Effective 25.17%",
    "section": "Ch37 — Key Formulas & Rates"
  },
  {
    "paper": "TX",
    "title": "Section 115BAB Rate",
    "eq": "15% + 10% surcharge + 4% cess = Effective 17.16%",
    "section": "Ch37 — Key Formulas & Rates"
  },
  {
    "paper": "TX",
    "title": "HRA Exemption (Minimum of 3)",
    "eq": "Min of: (1) Actual HRA received | (2) 50%/40% of salary (metro/non-metro) | (3) Actual rent − 10% of salary",
    "section": "Ch37 — Key Formulas & Rates"
  },
  {
    "paper": "ATX",
    "title": "Exemption Method",
    "eq": "Income taxed in the source country is fully EXEMPTED from tax in the residence country",
    "section": "Ch28 — Double Tax Relief Methods"
  },
  {
    "paper": "ATX",
    "title": "Credit Method (Most Common)",
    "eq": "Residence country taxes worldwide income but gives a CREDIT for tax already paid in the source country, up to the residence country's own tax rate on that income",
    "section": "Ch28 — Double Tax Relief Methods"
  },
  {
    "paper": "ATX",
    "title": "Deduction Method (Least Favourable)",
    "eq": "Foreign tax paid is simply deducted as an EXPENSE before calculating residence-country tax — provides only partial relief",
    "section": "Ch28 — Double Tax Relief Methods"
  },
  {
    "paper": "AA",
    "title": "Objective of an Audit",
    "eq": "To enable the auditor to express an opinion on whether the financial statements are prepared, in all material respects, in accordance with an applicable financial reporting framework (e.g. IFRS or local GAAP). Key phrase: \"in all material respects\" — not every single detail. Materiality limits the scope.",
    "section": "Ch34 — Official Definition — ISA 200"
  },
  {
    "paper": "AA",
    "title": "Level of Assurance",
    "eq": "REASONABLE assurance — not absolute assurance. Reasonable = high but not 100%. Absolute assurance is impossible due to: use of sampling, inherent limitations of internal controls, professional judgment involved in estimates, possibility of management override.",
    "section": "Ch34 — Official Definition — ISA 200"
  },
  {
    "paper": "AA",
    "title": "True and Fair View",
    "eq": "Financial statements present fairly the financial position, performance, and cash flows of an entity. \"True\" = factually accurate, supported by evidence. \"Fair\" = presented without bias, in accordance with GAAP/IFRS. This is the standard the auditor is assessing against.",
    "section": "Ch34 — Official Definition — ISA 200"
  },
  {
    "paper": "AA",
    "title": "Free From Material Misstatement",
    "eq": "Whether due to fraud OR error. Auditors must consider both. Error = unintentional mistake. Fraud = intentional misrepresentation. Auditors are not primarily fraud investigators but must maintain professional scepticism and respond when fraud risks are identified.",
    "section": "Ch34 — Official Definition — ISA 200"
  },
  {
    "paper": "AA",
    "title": "Overall Materiality — Common Benchmarks",
    "eq": "5% of Profit Before Tax (PBT) — most common for profitable entities 1% of Revenue — for low-margin businesses or where PBT is volatile 0.5–1% of Total Assets — for banks, holding companies, or asset-heavy entities 1–2% of Equity — for entities where equity is the key metric Choice of benchmark depends on what users focus on most. Professional judgement required.",
    "section": "Ch34 — Materiality — Benchmarks & Calculation"
  },
  {
    "paper": "AA",
    "title": "Performance Materiality",
    "eq": "Typically 60–75% of Overall Materiality Lower threshold used when designing procedures — so that the AGGREGATE of uncorrected misstatements does not exceed overall materiality. Acts as a buffer. If multiple small errors are found, their total might still be material.",
    "section": "Ch34 — Materiality — Benchmarks & Calculation"
  },
  {
    "paper": "AA",
    "title": "Clearly Trivial Threshold",
    "eq": "Typically 3–5% of Overall Materiality Misstatements below this level are clearly trivial and need not be investigated or accumulated. They cannot — even in aggregate — be material.",
    "section": "Ch34 — Materiality — Benchmarks & Calculation"
  },
  {
    "paper": "AA",
    "title": "Audit Risk (AR)",
    "eq": "AR = Inherent Risk (IR) × Control Risk (CR) × Detection Risk (DR) Auditor aims to keep AR at an acceptably low level. IR and CR are assessed — Detection Risk is manipulated by adjusting the nature/timing/extent of audit procedures.",
    "section": "Ch34 — The Audit Risk Model"
  },
  {
    "paper": "AA",
    "title": "Inherent Risk (IR)",
    "eq": "The susceptibility of an assertion to material misstatement BEFORE considering any controls. High IR examples: complex accounting estimates (fair value, provisions), subjective judgements, unusual transactions, high-volume/high-value transactions, industries prone to fraud (cash-heavy businesses, financial services), businesses under financial pressure.",
    "section": "Ch34 — The Audit Risk Model"
  },
  {
    "paper": "AA",
    "title": "Control Risk (CR)",
    "eq": "The risk that a material misstatement will NOT be prevented or detected by the entity's internal controls. High CR: weak internal controls, override of controls by management, no segregation of duties, inadequate IT controls. Low CR: strong, effective controls — allows auditor to reduce substantive testing.",
    "section": "Ch34 — The Audit Risk Model"
  },
  {
    "paper": "AA",
    "title": "Detection Risk (DR)",
    "eq": "The risk that the auditor's OWN PROCEDURES will fail to detect a material misstatement. This is what the AUDITOR CONTROLS. If IR and CR are high → auditor must REDUCE DR by doing more/better procedures. If IR and CR are low → can accept higher DR (do less testing). DR can never be zero — sampling means some items are never examined.",
    "section": "Ch34 — The Audit Risk Model"
  },
  {
    "paper": "AA",
    "title": "A — Analytical Procedures (ISA 520)",
    "eq": "Compare financial data to: prior year, budget, industry averages, expectations. Calculate ratios and investigate unusual fluctuations. Example: GP margin dropped from 35% to 22% → investigate reason → possible misstatement of revenue or cost of sales.",
    "section": "Ch34 — Audit Procedures — Full Toolkit"
  },
  {
    "paper": "AA",
    "title": "E — Enquiry",
    "eq": "Ask questions of management, staff, and third parties. Least reliable on its own — must be corroborated by other evidence. Example: Ask the warehouse manager about inventory obsolescence. Do not accept the answer alone — also physically inspect and check slow-moving items.",
    "section": "Ch34 — Audit Procedures — Full Toolkit"
  },
  {
    "paper": "AA",
    "title": "I — Inspection (Vouching & Tracing)",
    "eq": "Examine documents, records, physical assets. Vouching: start from recorded entry → find supporting document (tests EXISTENCE). Tracing: start from source document → check it is recorded (tests COMPLETENESS). Example: Select 50 sales invoices from the revenue ledger → trace to dispatch notes and customer orders (existence). Select dispatch notes → trace to sales ledger (completeness).",
    "section": "Ch34 — Audit Procedures — Full Toolkit"
  },
  {
    "paper": "AA",
    "title": "O — Observation",
    "eq": "Watch a process being performed by client staff. Limitation: behaviour may change when being observed. Example: Attend year-end inventory count — observe counting procedures, check for damaged goods, test counts independently. Observe controls operating in real time.",
    "section": "Ch34 — Audit Procedures — Full Toolkit"
  },
  {
    "paper": "AA",
    "title": "C — Confirmation (External)",
    "eq": "Obtain evidence directly from third parties — highly reliable. Examples: Bank confirmation letter (confirms balances, loans, contingent liabilities). Debtor circularisation (confirms receivable balances). Lawyer letters (confirms litigation, contingencies). Supplier statements (confirms payable balances).",
    "section": "Ch34 — Audit Procedures — Full Toolkit"
  },
  {
    "paper": "AA",
    "title": "R — Recalculation & Reperformance",
    "eq": "Recalculate: check mathematical accuracy of client's calculations. Reperformance: independently perform a procedure the client performs. Example: Recalculate depreciation charges, interest accruals, tax provisions, foreign currency translations. Reperform bank reconciliation independently.",
    "section": "Ch34 — Audit Procedures — Full Toolkit"
  },
  {
    "paper": "AA",
    "title": "Audit Objective",
    "eq": "Reasonable assurance that FS are free from material misstatement (fraud or error) → express opinion on true and fair view",
    "section": "Ch34 — Key Concepts Reference"
  },
  {
    "paper": "AA",
    "title": "Audit Risk Model",
    "eq": "AR = IR × CR × DR | Only DR is controlled by auditor | Higher IR/CR → Lower DR needed",
    "section": "Ch34 — Key Concepts Reference"
  },
  {
    "paper": "AA",
    "title": "Overall Materiality",
    "eq": "~5% PBT | ~1% Revenue | ~0.5% Assets (choose based on what users focus on)",
    "section": "Ch34 — Key Concepts Reference"
  },
  {
    "paper": "AA",
    "title": "Performance Materiality",
    "eq": "60–75% of Overall Materiality — used when designing procedures",
    "section": "Ch34 — Key Concepts Reference"
  },
  {
    "paper": "AA",
    "title": "Clearly Trivial",
    "eq": "3–5% of Overall Materiality — below this, no need to accumulate",
    "section": "Ch34 — Key Concepts Reference"
  },
  {
    "paper": "AA",
    "title": "Assertions",
    "eq": "Existence | Completeness | Valuation/Accuracy | Rights & Obligations | Cut-off | Presentation & Disclosure",
    "section": "Ch34 — Key Concepts Reference"
  },
  {
    "paper": "AA",
    "title": "Evidence Reliability",
    "eq": "Auditor-generated > External > Internal | Original > Copy | Written > Oral",
    "section": "Ch34 — Key Concepts Reference"
  },
  {
    "paper": "AA",
    "title": "FASSMO Threats",
    "eq": "Financial Interest | Advocacy | Self-Review | Self-Interest | Management Familiarity | Over-familiarity | Intimidation",
    "section": "Ch34 — Key Concepts Reference"
  },
  {
    "paper": "AA",
    "title": "Opinion Types",
    "eq": "Unmodified → Qualified (not pervasive) → Adverse (pervasive misstatement) | Disclaimer (pervasive scope limitation)",
    "section": "Ch34 — Key Concepts Reference"
  },
  {
    "paper": "AA",
    "title": "Going Concern",
    "eq": "ISA 570: Assess whether entity can continue 12+ months. Material uncertainty → EOM para. Doubt entity will continue → adverse/disclaimer depending on disclosure.",
    "section": "Ch34 — Key Concepts Reference"
  },
  {
    "paper": "AA",
    "title": "1. Authorisation",
    "eq": "The person who APPROVES a transaction e.g. Manager who approves a purchase order or payment",
    "section": "Ch35 — The Four Functions That Must Be Separated"
  },
  {
    "paper": "AA",
    "title": "2. Custody",
    "eq": "The person who has PHYSICAL CONTROL of the asset e.g. Cashier who handles cash; warehouse staff who control inventory",
    "section": "Ch35 — The Four Functions That Must Be Separated"
  },
  {
    "paper": "AA",
    "title": "3. Recording",
    "eq": "The person who RECORDS the transaction in the books e.g. Accounts payable clerk who posts invoices to the ledger",
    "section": "Ch35 — The Four Functions That Must Be Separated"
  },
  {
    "paper": "AA",
    "title": "4. Reconciliation",
    "eq": "The person who CHECKS and RECONCILES the records e.g. Finance manager who reviews bank reconciliations",
    "section": "Ch35 — The Four Functions That Must Be Separated"
  },
  {
    "paper": "FM",
    "title": "CAPM (Capital Asset Pricing Model)",
    "eq": "Ke = Rf + β(Rm − Rf) Rf = Risk-free rate (Government bond yield — typically 10-yr G-Sec rate in India) β (Beta) = Systematic risk of the share vs the market. β=1 moves with market. β>1 more volatile. β<1 less volatile. Rm = Expected market return (historical average stock market return) (Rm − Rf) = Equity Risk Premium (ERP) — extra return for taking equity risk vs risk-free",
    "section": "Ch22 — Cost of Equity — Two Models"
  },
  {
    "paper": "FM",
    "title": "Dividend Growth Model (Gordon Growth Model)",
    "eq": "Ke = D1/P0 + g D1 = Expected next dividend (D0 × (1+g)) P0 = Current share price (ex-dividend) g = Constant dividend growth rate (sustainable long-term growth) Used when: company pays regular dividends with stable growth rate",
    "section": "Ch22 — Cost of Equity — Two Models"
  },
  {
    "paper": "FM",
    "title": "Post-Tax Cost of Debt (Simple)",
    "eq": "Kd (post-tax) = Interest Rate × (1 − Tax Rate) Example: 10% loan, 25% tax rate → Kd = 10% × (1−0.25) = 7.5% The tax deductibility of interest reduces the effective cost by the tax rate.",
    "section": "Ch22 — Cost of Debt — Formulas"
  },
  {
    "paper": "FM",
    "title": "Yield to Maturity (YTM) — For Bonds/Debentures",
    "eq": "YTM = approximate IRR of bond cash flows YTM ≈ [Annual Coupon + (Redemption Value − Market Price)/n] ÷ [(Redemption Value + Market Price)/2] Used when bond trades at a discount or premium to face value. Market price reflects current required return, not the coupon rate. Post-tax YTM = YTM × (1−tax rate).",
    "section": "Ch22 — Cost of Debt — Formulas"
  },
  {
    "paper": "FM",
    "title": "Irredeemable Debt (Perpetual)",
    "eq": "Kd = Annual Interest / Market Price of Debt × (1 − Tax Rate) For perpetual bonds or irredeemable debentures — no redemption date.",
    "section": "Ch22 — Cost of Debt — Formulas"
  },
  {
    "paper": "FM",
    "title": "WACC",
    "eq": "WACC = Ke × [E/(E+D)] + Kd(1−T) × [D/(E+D)] Ke = Cost of Equity (from CAPM or DGM) Kd(1−T) = Post-tax Cost of Debt E = Market Value of Equity (shares outstanding × current share price) D = Market Value of Debt (market price of all debt instruments) E/(E+D) = Equity weight as proportion of total capital D/(E+D) = Debt weight as proportion of total capital Note: Always use MARKET values for weights — not book values",
    "section": "Ch22 — WACC Formula"
  },
  {
    "paper": "FM",
    "title": "Net Present Value (NPV)",
    "eq": "NPV = Σ [Cash Flow_t / (1+r)^t] − Initial Investment r = discount rate (WACC). t = time period. Sum all discounted cash flows and deduct initial outlay. Decision rule: Accept if NPV > 0. Maximise NPV when choosing between projects. NPV is the gold standard — directly measures value created in absolute ₹ terms. Theoretically superior to all other methods.",
    "section": "Ch22 — Investment Appraisal Methods — Formulas & Interpretation"
  },
  {
    "paper": "FM",
    "title": "Internal Rate of Return (IRR)",
    "eq": "IRR = discount rate that makes NPV = 0 Calculated by trial and error or interpolation: IRR ≈ a + [NPVa/(NPVa−NPVb)] × (b−a) Decision rule: Accept if IRR > Cost of Capital (WACC). Expresses return as a %, easy to compare to cost of capital. Limitation: may give multiple IRRs for non-conventional cash flows. Does not rank mutually exclusive projects correctly (use NPV instead).",
    "section": "Ch22 — Investment Appraisal Methods — Formulas & Interpretation"
  },
  {
    "paper": "FM",
    "title": "Payback Period",
    "eq": "Payback = Year before full recovery + (Remaining cost ÷ Cash flow in recovery year) Decision rule: Accept if Payback Simple, intuitive, focuses on liquidity and risk. Major limitation: ignores time value of money and cash flows after payback. Not theoretically sound but widely used in practice for quick screening.",
    "section": "Ch22 — Investment Appraisal Methods — Formulas & Interpretation"
  },
  {
    "paper": "FM",
    "title": "Discounted Payback Period",
    "eq": "Same as payback but uses discounted cash flows (PV of each year's CF) Improvement on simple payback — accounts for time value of money. Still ignores cash flows after payback date. Better than simple payback but inferior to NPV.",
    "section": "Ch22 — Investment Appraisal Methods — Formulas & Interpretation"
  },
  {
    "paper": "FM",
    "title": "Accounting Rate of Return (ARR)",
    "eq": "ARR = Average Annual Profit (after depreciation) ÷ Average Investment × 100 Average Investment = (Initial Investment + Scrap Value) ÷ 2 Decision rule: Accept if ARR > target rate. Higher ARR = better. Uses accounting profit, not cash flow. Ignores time value of money. Easy to calculate. Widely used by non-finance managers but theoretically weak. ACCA FM: know its limitations.",
    "section": "Ch22 — Investment Appraisal Methods — Formulas & Interpretation"
  },
  {
    "paper": "FM / AFM",
    "title": "Economic Order Quantity",
    "eq": "EOQ = √[(2 × D × Co) ÷ Ch] D = Annual Demand (units); Co = Cost per Order; Ch = Holding Cost per unit per year",
    "section": "Ch25 — EOQ Formula"
  },
  {
    "paper": "FM / AFM",
    "title": "Total Annual Ordering Cost",
    "eq": "(D ÷ EOQ) × Co",
    "section": "Ch25 — EOQ Formula"
  },
  {
    "paper": "FM / AFM",
    "title": "Total Annual Holding Cost",
    "eq": "(EOQ ÷ 2) × Ch",
    "section": "Ch25 — EOQ Formula"
  },
  {
    "paper": "FM / AFM",
    "title": "Key Insight at EOQ",
    "eq": "At the EOQ point, Total Ordering Cost EXACTLY EQUALS Total Holding Cost — this is the mathematical minimum of total inventory cost",
    "section": "Ch25 — EOQ Formula"
  },
  {
    "paper": "FM / AFM",
    "title": "Reorder Level (no uncertainty)",
    "eq": "Average Daily Usage × Lead Time (days)",
    "section": "Ch25 — Reorder & Safety Stock Formulas"
  },
  {
    "paper": "FM / AFM",
    "title": "Reorder Level (with safety stock)",
    "eq": "(Average Daily Usage × Lead Time) + Safety Stock",
    "section": "Ch25 — Reorder & Safety Stock Formulas"
  },
  {
    "paper": "FM / AFM",
    "title": "Maximum Stock Level",
    "eq": "Reorder Level + Reorder Quantity − (Minimum Usage × Minimum Lead Time)",
    "section": "Ch25 — Reorder & Safety Stock Formulas"
  },
  {
    "paper": "FM / AFM",
    "title": "Minimum Stock Level",
    "eq": "Reorder Level − (Average Usage × Average Lead Time)",
    "section": "Ch25 — Reorder & Safety Stock Formulas"
  },
  {
    "paper": "FM / AFM",
    "title": "Spread (Upper − Lower Limit)",
    "eq": "3 × [(0.75 × Transaction Cost × Variance of Daily Cash Flows) ÷ Interest Rate]^(1/3)",
    "section": "Ch25 — Miller-Orr Model Formulas"
  },
  {
    "paper": "FM / AFM",
    "title": "Return Point",
    "eq": "Lower Limit + (Spread ÷ 3)",
    "section": "Ch25 — Miller-Orr Model Formulas"
  },
  {
    "paper": "FM / AFM",
    "title": "Upper Limit",
    "eq": "Lower Limit + Spread",
    "section": "Ch25 — Miller-Orr Model Formulas"
  },
  {
    "paper": "Risk",
    "title": "Market Risk",
    "eq": "Risk of loss from adverse movements in market prices — interest rates, exchange rates, commodity prices, equity prices. Examples: Interest rate rise increases debt cost. Dollar strengthens vs Rupee — Indian exporter receives less in Rupee terms. Oil price spike increases production costs.",
    "section": "Ch36 — Three Main Categories of Financial Risk"
  },
  {
    "paper": "Risk",
    "title": "Credit Risk",
    "eq": "Risk that a counterparty (customer, borrower, investment issuer) fails to meet their financial obligations. Examples: Customer defaults on ₹5Cr receivable. Bank's loan portfolio suffers defaults. Bond issuer defaults. Swap counterparty fails to make payment.",
    "section": "Ch36 — Three Main Categories of Financial Risk"
  },
  {
    "paper": "Risk",
    "title": "Liquidity Risk",
    "eq": "Risk that the organisation cannot meet its financial obligations as they fall due — runs out of cash even if technically solvent. Examples: Company has large assets but cannot sell them fast enough to pay creditors. Bank faces sudden deposit withdrawals (bank run). Bond market seizes up — cannot roll over short-term debt.",
    "section": "Ch36 — Three Main Categories of Financial Risk"
  },
  {
    "paper": "Risk",
    "title": "Current Ratio",
    "eq": "Current Assets ÷ Current Liabilities Benchmark: >1 (assets exceed short-term obligations). Too high may indicate inefficient use of assets. Industry varies — retail often lower.",
    "section": "Ch36 — Key Liquidity Ratios"
  },
  {
    "paper": "Risk",
    "title": "Quick Ratio (Acid Test)",
    "eq": "(Current Assets − Inventory) ÷ Current Liabilities More conservative — excludes inventory (least liquid current asset). Benchmark: >1 for most industries.",
    "section": "Ch36 — Key Liquidity Ratios"
  },
  {
    "paper": "Risk",
    "title": "Cash Ratio",
    "eq": "(Cash + Short-term Investments) ÷ Current Liabilities Most conservative — only cash and near-cash. Shows ability to meet obligations with immediately available funds.",
    "section": "Ch36 — Key Liquidity Ratios"
  },
  {
    "paper": "Risk",
    "title": "Cash Conversion Cycle (CCC)",
    "eq": "Receivable Days + Inventory Days − Payable Days How long cash is tied up in the operating cycle. Lower = better. Negative CCC (e.g. Amazon, supermarkets) = customers pay before suppliers are paid — excellent liquidity position.",
    "section": "Ch36 — Key Liquidity Ratios"
  },
  {
    "paper": "Risk",
    "title": "Risk Appetite",
    "eq": "The AMOUNT and TYPE of risk an organisation is WILLING to accept in pursuit of its objectives. Set by the Board. Expressed qualitatively (\"we do not accept regulatory compliance risk\") or quantitatively (\"maximum credit loss of ₹50Cr per year\"). Aligns risk-taking with strategy.",
    "section": "Ch36 — Risk Appetite, Tolerance & Capacity — Defined"
  },
  {
    "paper": "Risk",
    "title": "Risk Tolerance",
    "eq": "The ACCEPTABLE VARIATION around risk appetite — the boundaries within which risk must stay. Example: Appetite = 5% NPL ratio. Tolerance = up to 6% before escalation required. Between 5–6% = monitor closely. Above 6% = breach → immediate action.",
    "section": "Ch36 — Risk Appetite, Tolerance & Capacity — Defined"
  },
  {
    "paper": "Risk",
    "title": "Risk Capacity",
    "eq": "The MAXIMUM amount of risk the organisation CAN bear — before its survival is threatened. Determined by financial strength, regulatory capital, stakeholder expectations. Risk appetite should always be LESS than risk capacity — there must be a buffer.",
    "section": "Ch36 — Risk Appetite, Tolerance & Capacity — Defined"
  },
  {
    "paper": "Risk",
    "title": "Risk Attitude",
    "eq": "The overall disposition of the organisation towards risk — Risk Averse, Risk Neutral, or Risk Seeking. A startup is risk-seeking (high growth, accept high risk). A bank is typically risk-averse (depositors' money, regulatory capital). A utility company is risk-neutral to averse.",
    "section": "Ch36 — Risk Appetite, Tolerance & Capacity — Defined"
  },
  {
    "paper": "Risk",
    "title": "Risk Score (Matrix)",
    "eq": "Risk Score = Likelihood (1–5) × Impact (1–5) | Range 1–25 | Higher = more critical",
    "section": "Ch36 — Key Formulas & Concepts"
  },
  {
    "paper": "Risk",
    "title": "Current Ratio",
    "eq": "Current Assets ÷ Current Liabilities | Target: >1",
    "section": "Ch36 — Key Formulas & Concepts"
  },
  {
    "paper": "Risk",
    "title": "Quick Ratio",
    "eq": "(Current Assets − Inventory) ÷ Current Liabilities | More conservative than current ratio",
    "section": "Ch36 — Key Formulas & Concepts"
  },
  {
    "paper": "Risk",
    "title": "Cash Conversion Cycle",
    "eq": "Receivable Days + Inventory Days − Payable Days | Lower = better liquidity",
    "section": "Ch36 — Key Formulas & Concepts"
  },
  {
    "paper": "Risk",
    "title": "Capital Adequacy Ratio (Banks)",
    "eq": "Tier 1 + Tier 2 Capital ÷ Risk-Weighted Assets | Minimum 9% in India (Basel III)",
    "section": "Ch36 — Key Formulas & Concepts"
  },
  {
    "paper": "Risk",
    "title": "Expected Loss (Credit Risk)",
    "eq": "EL = PD × LGD × EAD | PD = Probability of Default | LGD = Loss Given Default | EAD = Exposure at Default",
    "section": "Ch36 — Key Formulas & Concepts"
  },
  {
    "paper": "Risk",
    "title": "Beta (Systematic Risk)",
    "eq": "β = Cov(Ri, Rm) ÷ Var(Rm) | β > 1: more volatile than market | β < 1: less volatile | β = 0: no market risk",
    "section": "Ch36 — Key Formulas & Concepts"
  },
  {
    "paper": "FM",
    "title": "Depreciation (SLM)",
    "eq": "Opening Gross PP&E ÷ Useful Life — feeds the P&L D&A line",
    "section": "Ch21 — Financial Modelling Build Logic"
  },
  {
    "paper": "FM",
    "title": "Average Balance (for interest calcs)",
    "eq": "(Opening + Closing) ÷ 2 — or use Opening only to avoid circularity in the model",
    "section": "Ch21 — Financial Modelling Build Logic"
  },
  {
    "paper": "FM",
    "title": "Interest Expense",
    "eq": "Average Debt × Interest Rate — feeds the P&L Finance Costs line",
    "section": "Ch21 — Financial Modelling Build Logic"
  },
  {
    "paper": "FM",
    "title": "Receivables Balance (from Days)",
    "eq": "(Receivable Days ÷ 365) × Revenue",
    "section": "Ch21 — Financial Modelling Build Logic"
  },
  {
    "paper": "FM",
    "title": "Inventory Balance (from Days)",
    "eq": "(Inventory Days ÷ 365) × COGS",
    "section": "Ch21 — Financial Modelling Build Logic"
  },
  {
    "paper": "FM",
    "title": "Payables Balance (from Days)",
    "eq": "(Payable Days ÷ 365) × COGS",
    "section": "Ch21 — Financial Modelling Build Logic"
  },
  {
    "paper": "FM",
    "title": "Annualised Cost of Discount NOT Taken",
    "eq": "[d ÷ (1−d)] × [365 ÷ (N − discount period)] — where d = discount %, N = normal credit period. Compare this to the cost of finance to decide whether taking the discount is worthwhile.",
    "section": "Ch22 — Early Payment Discount Evaluation"
  },
  {
    "paper": "SBL",
    "title": "Market Penetration",
    "eq": "Existing Products + Existing Markets — LOWEST risk. Grow through increased market share, more frequent purchase, or winning customers from competitors within a familiar market.",
    "section": "Ch31 — The Four Ansoff Quadrants"
  },
  {
    "paper": "SBL",
    "title": "Market Development",
    "eq": "Existing Products + New Markets — MODERATE risk. Take a proven product into new geographies, new customer segments, or new use cases.",
    "section": "Ch31 — The Four Ansoff Quadrants"
  },
  {
    "paper": "SBL",
    "title": "Product Development",
    "eq": "New Products + Existing Markets — MODERATE risk. Leverage existing customer relationships and market knowledge to launch new products.",
    "section": "Ch31 — The Four Ansoff Quadrants"
  },
  {
    "paper": "SBL",
    "title": "Diversification",
    "eq": "New Products + New Markets — HIGHEST risk. Can be RELATED (leveraging some existing capability/synergy) or UNRELATED (a completely new business area, highest risk of all).",
    "section": "Ch31 — The Four Ansoff Quadrants"
  },
  {
    "paper": "SBL",
    "title": "Suitability",
    "eq": "Does the strategy actually address the strategic issues identified (from SWOT/PESTEL/Five Forces analysis)? Does it fit the organisation's overall objectives and capabilities?",
    "section": "Ch31 — The SAF Evaluation Criteria"
  },
  {
    "paper": "SBL",
    "title": "Acceptability",
    "eq": "Will the strategy deliver acceptable RETURNS (financial appraisal — NPV, ROI), acceptable RISK levels, and be acceptable to key STAKEHOLDERS (shareholders, employees, regulators)?",
    "section": "Ch31 — The SAF Evaluation Criteria"
  },
  {
    "paper": "SBL",
    "title": "Feasibility",
    "eq": "Does the organisation actually have (or can it obtain) the RESOURCES and CAPABILITIES needed to execute the strategy — finance, people, technology, time?",
    "section": "Ch31 — The SAF Evaluation Criteria"
  },
  {
    "paper": "SBL",
    "title": "Principals",
    "eq": "Shareholders — they OWN the company but don't manage it day-to-day Want: maximum long-term shareholder value, sustainable returns, transparency, dividends. Risk-tolerant (diversified portfolio). Long-term view.",
    "section": "Ch38 — The Agency Problem — Core Framework"
  },
  {
    "paper": "SBL",
    "title": "Agents",
    "eq": "Directors and Management — they RUN the company on behalf of shareholders May want: personal wealth maximisation, job security, prestige, empire building. Risk-averse (concentrated human capital in one company). Potentially short-term view (linked to bonus cycle).",
    "section": "Ch38 — The Agency Problem — Core Framework"
  },
  {
    "paper": "SBL",
    "title": "Agency Costs",
    "eq": "Costs arising from the separation of ownership and control Monitoring costs (audit, board oversight, shareholder meetings), Bonding costs (management incentive schemes, employment contracts), Residual loss (value destroyed by management self-interest even after monitoring).",
    "section": "Ch38 — The Agency Problem — Core Framework"
  },
  {
    "paper": "SBL",
    "title": "Governance Solution",
    "eq": "Mechanisms to align agent behaviour with principal interests Independent board oversight, performance-linked remuneration, shareholder voting rights, audit and disclosure requirements, regulatory enforcement. Goal: minimise residual agency loss.",
    "section": "Ch38 — The Agency Problem — Core Framework"
  },
  {
    "paper": "SBL / APM",
    "title": "1-2: Build Urgency & Coalition",
    "eq": "Create a genuine sense of urgency for change; assemble a powerful enough guiding coalition of influential supporters",
    "section": "Ch32 — Kotter's 8 Steps"
  },
  {
    "paper": "SBL / APM",
    "title": "3-4: Vision & Communication",
    "eq": "Develop a clear change vision and strategy; communicate that vision relentlessly through every available channel",
    "section": "Ch32 — Kotter's 8 Steps"
  },
  {
    "paper": "SBL / APM",
    "title": "5-6: Empower & Early Wins",
    "eq": "Remove obstacles and empower broad-based action; generate visible SHORT-TERM WINS to build momentum and credibility",
    "section": "Ch32 — Kotter's 8 Steps"
  },
  {
    "paper": "SBL / APM",
    "title": "7-8: Consolidate & Anchor",
    "eq": "Consolidate gains and produce more change, rather than declaring victory too early; anchor new approaches firmly in the organisational culture",
    "section": "Ch32 — Kotter's 8 Steps"
  },
  {
    "paper": "SBR",
    "title": "Cumulative Expense to Date",
    "eq": "(Number of Options Expected to Vest × Fair Value at Grant Date) × (Years Elapsed ÷ Total Vesting Period)",
    "section": "Ch30 — Equity-Settled SBP Formula"
  },
  {
    "paper": "SBR",
    "title": "Expense for the Current Year",
    "eq": "Cumulative Expense to Date (this year) − Cumulative Expense Recognised (prior years)",
    "section": "Ch30 — Equity-Settled SBP Formula"
  },
  {
    "paper": "SBR",
    "title": "Assets & Liabilities (Balance Sheet)",
    "eq": "Translated at the CLOSING rate (rate at the reporting date)",
    "section": "Ch30 — Translation Rules (IAS 21)"
  },
  {
    "paper": "SBR",
    "title": "Income & Expenses (P&L)",
    "eq": "Translated at the rate ruling AT THE DATE OF THE TRANSACTION — in practice, often an average rate for the period is used as a reasonable approximation",
    "section": "Ch30 — Translation Rules (IAS 21)"
  },
  {
    "paper": "SBR",
    "title": "Resulting Exchange Difference",
    "eq": "Goes to OTHER COMPREHENSIVE INCOME (a separate \"Foreign Currency Translation Reserve\" within equity) — NOT through profit or loss",
    "section": "Ch30 — Translation Rules (IAS 21)"
  },
  {
    "paper": "AFM",
    "title": "Adjusted Present Value",
    "eq": "APV = Base Case NPV (all-equity, discounted at ungeared cost of equity) + PV of Financing Side-Effects",
    "section": "Ch26 — APV Formula"
  },
  {
    "paper": "AFM",
    "title": "Financing Side-Effects Include",
    "eq": "PV of Tax Shield on Debt Interest + PV of Issue Costs + PV of Subsidised Loan Benefits (if any) − PV of Financial Distress Costs",
    "section": "Ch26 — APV Formula"
  },
  {
    "paper": "AFM",
    "title": "Ungeared Cost of Equity (via CAPM)",
    "eq": "First \"ungear\" the observed geared beta to an asset (ungeared) beta, then apply CAPM to get the discount rate for the base-case cash flows",
    "section": "Ch26 — APV Formula"
  },
  {
    "paper": "AFM",
    "title": "Value of Synergy",
    "eq": "Value of Combined Entity − (Value of Acquirer Standalone + Value of Target Standalone)",
    "section": "Ch26 — Key M&A Valuation Formulas"
  },
  {
    "paper": "AFM",
    "title": "Maximum Justifiable Premium",
    "eq": "Target's Standalone Value + Value of Synergies − Deal/Integration Costs",
    "section": "Ch26 — Key M&A Valuation Formulas"
  },
  {
    "paper": "AFM",
    "title": "Gain to Target Shareholders",
    "eq": "Premium Paid Over Standalone Target Value",
    "section": "Ch26 — Key M&A Valuation Formulas"
  },
  {
    "paper": "AFM",
    "title": "Gain to Acquirer Shareholders",
    "eq": "Total Synergy Value − Premium Paid to Target",
    "section": "Ch26 — Key M&A Valuation Formulas"
  },
  {
    "paper": "AFM",
    "title": "EBIT (Earnings Before Interest & Tax)",
    "eq": "Revenue − COGS − Operating Expenses − D&A This is operating profit — the return generated by the business before financing costs and tax.",
    "section": "Ch33 — FCFF Build — From P&L and Balance Sheet"
  },
  {
    "paper": "AFM",
    "title": "NOPAT (Net Operating Profit After Tax)",
    "eq": "EBIT × (1 − Tax Rate) Tax-adjusted operating profit. Removes the tax benefit of debt interest — treats firm as if all equity financed (tax effect captured in WACC separately).",
    "section": "Ch33 — FCFF Build — From P&L and Balance Sheet"
  },
  {
    "paper": "AFM",
    "title": "+ Depreciation & Amortisation",
    "eq": "Add back D&A (non-cash charge) D&A reduced EBIT but did not consume cash — we add it back to get to cash earnings.",
    "section": "Ch33 — FCFF Build — From P&L and Balance Sheet"
  },
  {
    "paper": "AFM",
    "title": "− Capital Expenditure (Capex)",
    "eq": "Subtract investment in PP&E and other long-term assets Cash actually spent on maintaining and growing the asset base. From cash flow statement or capex schedule.",
    "section": "Ch33 — FCFF Build — From P&L and Balance Sheet"
  },
  {
    "paper": "AFM",
    "title": "− / + Change in Working Capital",
    "eq": "−ΔInventory − ΔReceivables + ΔPayables Growing businesses often need more working capital — this consumes cash. Shrinking WC (e.g. reducing receivables) releases cash.",
    "section": "Ch33 — FCFF Build — From P&L and Balance Sheet"
  },
  {
    "paper": "AFM",
    "title": "= Free Cash Flow to Firm (FCFF)",
    "eq": "NOPAT + D&A − Capex − ΔNWC The cash the business generates after all operating investments. Available to be distributed to both debt and equity holders — hence \"to firm.\"",
    "section": "Ch33 — FCFF Build — From P&L and Balance Sheet"
  },
  {
    "paper": "AFM",
    "title": "WACC",
    "eq": "WACC = Ke × [E/(E+D)] + Kd(1−t) × [D/(E+D)] Ke = Cost of Equity (from CAPM: Rf + β(Rm−Rf)) Kd = Pre-tax cost of debt (interest rate or YTM on debt) t = Corporate tax rate E = Market value of equity | D = Market value of debt Always use MARKET values for weights, never book values.",
    "section": "Ch33 — WACC Formula — Recap"
  },
  {
    "paper": "AFM",
    "title": "Method 1 — Gordon Growth Model (GGM)",
    "eq": "TV = FCFFn × (1 + g) ÷ (WACC − g) FCFFn = Free Cash Flow in final forecast year g = Long-term sustainable growth rate (usually GDP growth or inflation rate — 3–5% typically) WACC − g = the \"spread\" — must be positive (WACC must exceed g or formula breaks) Key rule: g should never exceed long-run GDP growth — no company can grow faster than the economy forever",
    "section": "Ch33 — Terminal Value — Two Methods"
  },
  {
    "paper": "AFM",
    "title": "Method 2 — Exit Multiple",
    "eq": "TV = Final Year EBITDA × EV/EBITDA Multiple Multiple = current trading multiple of comparable companies (EV/EBITDA, EV/EBIT, P/E) More pragmatic — anchored to real market pricing But introduces circular logic: if multiples compress (as in a bear market), TV falls dramatically Commonly used by investment bankers and PE analysts in LBO models",
    "section": "Ch33 — Terminal Value — Two Methods"
  },
  {
    "paper": "AFM",
    "title": "Book NAV (Accounting)",
    "eq": "Total Equity on Balance Sheet = Total Assets − Total Liabilities At historical cost. Quick but not meaningful for valuation purposes — ignores fair value changes in assets.",
    "section": "Ch33 — Net Asset Value (NAV) Calculation"
  },
  {
    "paper": "AFM",
    "title": "Adjusted NAV (Fair Value)",
    "eq": "Fair Value of All Assets − Fair Value of All Liabilities Revalue each asset class to current market/fair value (PP&E, investments, real estate, intangibles). Adjust liabilities for current market value of debt. This gives the true economic net asset value per share.",
    "section": "Ch33 — Net Asset Value (NAV) Calculation"
  },
  {
    "paper": "AFM",
    "title": "NAV Per Share",
    "eq": "Adjusted NAV ÷ Shares Outstanding Compare to current share price. P/B = Share Price ÷ NAV per share. P/B < 1 means market prices company below its net assets — unusual for profitable companies, common for distressed or capital-destroying businesses.",
    "section": "Ch33 — Net Asset Value (NAV) Calculation"
  },
  {
    "paper": "AFM",
    "title": "Enterprise Value (EV)",
    "eq": "EV = Market Cap + Total Debt + Preference Shares + Minority Interest − Cash & Cash Equivalents EV is the TOTAL value of the business — what you would pay to buy the whole company (all equity + all debt) and then receive the cash sitting in it. Capital structure neutral.",
    "section": "Ch33 — The EV ↔ Equity Value Bridge"
  },
  {
    "paper": "AFM",
    "title": "From EV → Equity Value",
    "eq": "Equity Value = EV − Total Debt − Preference Shares − Minority Interest + Cash Alternatively: EV − Net Debt (where Net Debt = Total Debt − Cash). This is what is left for equity shareholders after all debt obligations are accounted for.",
    "section": "Ch33 — The EV ↔ Equity Value Bridge"
  },
  {
    "paper": "AFM",
    "title": "From Equity Value → Share Price",
    "eq": "Intrinsic Share Price = Equity Value ÷ Diluted Shares Outstanding Use DILUTED shares — include options, warrants, convertibles that could dilute equity. This is what the stock is worth per share — compare to market price.",
    "section": "Ch33 — The EV ↔ Equity Value Bridge"
  },
  {
    "paper": "AFM",
    "title": "Free Cash Flow to Firm (FCFF)",
    "eq": "FCFF = EBIT × (1−t) + D&A − Capex − ΔNWC Or: NOPAT + D&A − Capex − ΔNWC",
    "section": "Ch33 — Complete Formula Sheet"
  },
  {
    "paper": "AFM",
    "title": "WACC",
    "eq": "WACC = Ke × [E/(E+D)] + Kd(1−t) × [D/(E+D)] Always: market value weights, post-tax cost of debt",
    "section": "Ch33 — Complete Formula Sheet"
  },
  {
    "paper": "AFM",
    "title": "Cost of Equity (CAPM)",
    "eq": "Ke = Rf + β(Rm − Rf)",
    "section": "Ch33 — Complete Formula Sheet"
  },
  {
    "paper": "AFM",
    "title": "Terminal Value — Gordon Growth Model",
    "eq": "TV = FCFFn × (1+g) ÷ (WACC − g) Condition: g < WACC always",
    "section": "Ch33 — Complete Formula Sheet"
  },
  {
    "paper": "AFM",
    "title": "Terminal Value — Exit Multiple",
    "eq": "TV = Final Year EBITDA × EV/EBITDA Multiple",
    "section": "Ch33 — Complete Formula Sheet"
  },
  {
    "paper": "AFM",
    "title": "PV of any Cash Flow",
    "eq": "PV = Cash Flow ÷ (1 + WACC)^n n = number of years from today",
    "section": "Ch33 — Complete Formula Sheet"
  },
  {
    "paper": "AFM",
    "title": "Enterprise Value (from market)",
    "eq": "EV = Market Cap + Total Debt + Pref Shares + Minority Interest − Cash",
    "section": "Ch33 — Complete Formula Sheet"
  },
  {
    "paper": "AFM",
    "title": "Equity Value (from EV)",
    "eq": "Equity Value = EV − Net Debt Net Debt = Total Debt − Cash",
    "section": "Ch33 — Complete Formula Sheet"
  },
  {
    "paper": "AFM",
    "title": "Intrinsic Share Price",
    "eq": "Share Price = Equity Value ÷ Diluted Shares Outstanding",
    "section": "Ch33 — Complete Formula Sheet"
  },
  {
    "paper": "AFM",
    "title": "P/E Ratio",
    "eq": "P/E = Share Price ÷ Earnings Per Share (EPS)",
    "section": "Ch33 — Complete Formula Sheet"
  },
  {
    "paper": "AFM",
    "title": "EV/EBITDA Multiple",
    "eq": "EV/EBITDA = Enterprise Value ÷ EBITDA",
    "section": "Ch33 — Complete Formula Sheet"
  },
  {
    "paper": "AFM",
    "title": "Price to Book (P/B)",
    "eq": "P/B = Market Cap ÷ Book Value of Equity Or: Share Price ÷ Book Value Per Share",
    "section": "Ch33 — Complete Formula Sheet"
  },
  {
    "paper": "AFM",
    "title": "Implied P/B from Fundamentals",
    "eq": "P/B = (ROE − g) ÷ (Ke − g) Higher ROE → deserves higher P/B. If ROE = Ke → P/B = 1",
    "section": "Ch33 — Complete Formula Sheet"
  },
  {
    "paper": "AFM",
    "title": "NAV Per Share",
    "eq": "NAV/Share = (Fair Value of Assets − Fair Value of Liabilities) ÷ Shares Outstanding",
    "section": "Ch33 — Complete Formula Sheet"
  },
  {
    "paper": "AFM",
    "title": "Margin of Safety",
    "eq": "Margin of Safety = (Intrinsic Value − Market Price) ÷ Intrinsic Value × 100%",
    "section": "Ch33 — Complete Formula Sheet"
  },
  {
    "paper": "AFM",
    "title": "EV/Revenue Multiple",
    "eq": "EV/Revenue = Enterprise Value ÷ Revenue — useful for early-stage or loss-making companies where EBITDA/EBIT multiples aren't meaningful",
    "section": "Ch33 — Complete Formula Sheet"
  },
  {
    "paper": "AFM",
    "title": "EV/EBIT Multiple",
    "eq": "EV/EBIT = Enterprise Value ÷ EBIT — captures depreciation/capex differences that EV/EBITDA ignores, useful for capital-intensive businesses",
    "section": "Ch33 — Complete Formula Sheet"
  },
  {
    "paper": "APM",
    "title": "Return on Investment (ROI)",
    "eq": "Divisional Profit ÷ Divisional Capital Employed × 100",
    "section": "Ch27 — Divisional Performance Formulas"
  },
  {
    "paper": "APM",
    "title": "Residual Income (RI)",
    "eq": "Divisional Profit − (Divisional Capital Employed × Company's Required/Cost of Capital Rate)",
    "section": "Ch27 — Divisional Performance Formulas"
  },
  {
    "paper": "APM",
    "title": "EVA",
    "eq": "NOPAT (Net Operating Profit After Tax, Adjusted) − (WACC × Adjusted Capital Employed)",
    "section": "Ch27 — EVA Formula"
  },
  {
    "paper": "APM",
    "title": "Common Adjustments",
    "eq": "Add back R&D expenditure (capitalise it, since it creates future economic value like an asset); adjust for operating leases; remove non-cash provisions' distorting effects",
    "section": "Ch27 — EVA Formula"
  },
  {
    "paper": "APM",
    "title": "Market Price Basis",
    "eq": "Transfer Price = the price the selling division could get selling externally — best when a genuine external market exists",
    "section": "Ch27 — Transfer Pricing Methods"
  },
  {
    "paper": "APM",
    "title": "Full Cost Basis",
    "eq": "Transfer Price = Full Absorption Cost of Production — selling division earns NO profit on internal sales, which can be demotivating",
    "section": "Ch27 — Transfer Pricing Methods"
  },
  {
    "paper": "APM",
    "title": "Cost-Plus Basis",
    "eq": "Transfer Price = Cost + a Profit Margin — fairer than pure cost, but the margin % itself is often contested between divisions",
    "section": "Ch27 — Transfer Pricing Methods"
  },
  {
    "paper": "AAA",
    "title": "Overall Materiality",
    "eq": "The threshold above which misstatements, individually or in aggregate, could reasonably influence users' economic decisions — typically set as a % of a benchmark (revenue, profit, or total assets, depending on the entity's nature)",
    "section": "Ch29 — Materiality Concepts"
  },
  {
    "paper": "AAA",
    "title": "Performance Materiality",
    "eq": "Set LOWER than overall materiality — a buffer that reduces the risk that the sum of many individually immaterial misstatements could aggregate to a material amount",
    "section": "Ch29 — Materiality Concepts"
  },
  {
    "paper": "AAA",
    "title": "Specific Materiality",
    "eq": "A LOWER materiality level applied to particular classes of transactions/balances where even smaller misstatements could reasonably influence users (e.g. related party transactions, director remuneration)",
    "section": "Ch29 — Materiality Concepts"
  },
  {
    "paper": "AAA",
    "title": "Unmodified (Unqualified)",
    "eq": "Financial statements give a true and fair view in all material respects — no significant issues found",
    "section": "Ch29 — The Complete Opinion Decision Framework"
  },
  {
    "paper": "AAA",
    "title": "Qualified (\"Except For\")",
    "eq": "Used when a misstatement or scope limitation is MATERIAL but NOT PERVASIVE — the issue is significant but contained/isolated",
    "section": "Ch29 — The Complete Opinion Decision Framework"
  },
  {
    "paper": "AAA",
    "title": "Adverse",
    "eq": "Used when a misstatement is BOTH MATERIAL AND PERVASIVE — the financial statements as a whole are misleading, not just one isolated area",
    "section": "Ch29 — The Complete Opinion Decision Framework"
  },
  {
    "paper": "AAA",
    "title": "Disclaimer of Opinion",
    "eq": "Used when a SCOPE LIMITATION is both material and pervasive — the auditor simply cannot obtain enough evidence to form ANY opinion",
    "section": "Ch29 — The Complete Opinion Decision Framework"
  },
  {
    "paper": "FM",
    "title": "IF / IFS / IFERROR",
    "eq": "=IF(year>=start_year, revenue*margin, 0) =IFERROR(EBIT/Interest, \"N/A\") Conditional logic throughout models. IF for business rules (tax only when PBT positive). IFERROR to handle divide-by-zero in early years or loss years — keeps model clean.",
    "section": "Ch21 — Must-Know Excel Functions — With Modelling Context"
  },
  {
    "paper": "FM",
    "title": "XLOOKUP",
    "eq": "=XLOOKUP(year, years_header_row, values_row, \"N/A\") Pull specific year's assumption or output. Used in Scenario Manager to pull the right assumption set. Replaced VLOOKUP — use XLOOKUP in all new models.",
    "section": "Ch21 — Must-Know Excel Functions — With Modelling Context"
  },
  {
    "paper": "FM",
    "title": "INDEX / MATCH",
    "eq": "=INDEX(data_range, MATCH(lookup_value, lookup_range, 0)) More flexible than XLOOKUP for two-dimensional lookups. Used when pulling data from comparable company tables or historical data with both row and column references.",
    "section": "Ch21 — Must-Know Excel Functions — With Modelling Context"
  },
  {
    "paper": "FM",
    "title": "SUMIF / SUMIFS",
    "eq": "=SUMIFS(amount_col, category_col, \"Revenue\", year_col, 2025) Aggregate financial data by multiple criteria. Used in revenue build (sum revenue by product line and year), cost aggregation by department. Essential for models pulling from large data tables.",
    "section": "Ch21 — Must-Know Excel Functions — With Modelling Context"
  },
  {
    "paper": "FM",
    "title": "CHOOSE",
    "eq": "=CHOOSE(Assumptions!$B$2, base_value, bull_value, bear_value) The scenario selector function. Cell B2 contains 1/2/3 from dropdown. CHOOSE returns the right scenario's assumption. Cleaner than nested IFs for 3-scenario models.",
    "section": "Ch21 — Must-Know Excel Functions — With Modelling Context"
  },
  {
    "paper": "FM",
    "title": "OFFSET",
    "eq": "=OFFSET(start_cell, rows_down, cols_right) Dynamic range reference that shifts based on inputs. Used in rolling forecast models where the \"current month\" reference moves forward each month. Also used for dynamic chart ranges.",
    "section": "Ch21 — Must-Know Excel Functions — With Modelling Context"
  },
  {
    "paper": "FM",
    "title": "NPV",
    "eq": "=NPV(discount_rate, cashflow_year1:cashflow_year5) + initial_investment Net Present Value of future cash flows. Core formula in DCF valuation (Chapter 33). Note: NPV() in Excel discounts from period 1 — add Year 0 investment separately (it is already at present value).",
    "section": "Ch21 — Must-Know Excel Functions — With Modelling Context"
  },
  {
    "paper": "FM",
    "title": "IRR / XIRR",
    "eq": "=IRR(cashflow_range) =XIRR(cashflow_range, dates_range) Internal Rate of Return. Used in investment appraisal, LBO return calculations, project finance models. XIRR is more accurate — uses actual dates rather than assuming equal periods.",
    "section": "Ch21 — Must-Know Excel Functions — With Modelling Context"
  },
  {
    "paper": "FM",
    "title": "MAX / MIN",
    "eq": "=MAX(0, EBIT) — floor at zero =MIN(cash_balance, debt_repayment) — can't repay more than cash available Critical for model logic constraints. Tax cannot be negative (use MAX(0, PBT × tax_rate)). Debt cannot go below zero. Cash surplus cannot exceed revolving credit limit. These prevent model from showing impossible outputs.",
    "section": "Ch21 — Must-Know Excel Functions — With Modelling Context"
  },
  {
    "paper": "FM",
    "title": "Data Validation (Dropdowns)",
    "eq": "Data → Data Validation → List → \"Base,Bull,Bear\" Creates scenario selector dropdown. Links to CHOOSE function. Makes model user-friendly for non-modellers — CFO selects scenario from dropdown, all outputs update automatically without touching formulas.",
    "section": "Ch21 — Must-Know Excel Functions — With Modelling Context"
  },
  {
    "paper": "FM",
    "title": "Conditional Formatting",
    "eq": "Home → Conditional Formatting → Highlight Rules Format Checks tab: green when balanced, red when not. Highlight negative cash balances in red. Highlight cells exceeding thresholds (e.g. gearing > 70% turns red). Makes model self-annotating — errors and risks are visually obvious.",
    "section": "Ch21 — Must-Know Excel Functions — With Modelling Context"
  },
  {
    "paper": "FM",
    "title": "What-If Data Table",
    "eq": "Data → What-If Analysis → Data Table (1 or 2 variable) Builds sensitivity grids automatically. Row input = Revenue Growth %. Column input = EBITDA Margin %. Output = EBITDA for every combination. Essential for sensitivity analysis section of any model.",
    "section": "Ch21 — Must-Know Excel Functions — With Modelling Context"
  },
  {
    "paper": "EXCEL",
    "title": "SUM / SUMPRODUCT",
    "eq": "=SUM(A1:A10) — adds a range =SUMPRODUCT(A1:A10,B1:B10) — multiplies arrays and sums. Used for weighted averages, portfolio calculations, WACC. SUMPRODUCT is one of the most powerful functions in finance — replaces many complex array formulas.",
    "section": "Ch39 — Mathematical & Statistical Functions"
  },
  {
    "paper": "EXCEL",
    "title": "AVERAGE / MEDIAN / MODE",
    "eq": "=AVERAGE(A1:A10) — arithmetic mean =MEDIAN(A1:A10) — middle value (more robust than mean for skewed data) =MODE(A1:A10) — most frequent value",
    "section": "Ch39 — Mathematical & Statistical Functions"
  },
  {
    "paper": "EXCEL",
    "title": "MIN / MAX / LARGE / SMALL",
    "eq": "=MIN(A1:A10) / =MAX(A1:A10) — minimum and maximum =LARGE(A1:A10,2) — 2nd largest value =SMALL(A1:A10,3) — 3rd smallest value",
    "section": "Ch39 — Mathematical & Statistical Functions"
  },
  {
    "paper": "EXCEL",
    "title": "ABS / ROUND / ROUNDUP / ROUNDDOWN",
    "eq": "=ABS(A1) — absolute value (removes negative sign) =ROUND(A1,2) — rounds to 2 decimal places =ROUNDUP(A1,0) — always rounds up (e.g. for ceiling calculations) =ROUNDDOWN(A1,0) — always rounds down",
    "section": "Ch39 — Mathematical & Statistical Functions"
  },
  {
    "paper": "EXCEL",
    "title": "COUNT / COUNTA / COUNTBLANK",
    "eq": "=COUNT(A1:A10) — counts numbers only =COUNTA(A1:A10) — counts non-empty cells (numbers and text) =COUNTBLANK(A1:A10) — counts empty cells Essential for data quality checks — verify expected number of rows/columns.",
    "section": "Ch39 — Mathematical & Statistical Functions"
  },
  {
    "paper": "EXCEL",
    "title": "SUBTOTAL",
    "eq": "=SUBTOTAL(9,A1:A100) — SUM that ignores hidden rows (function_num 9=SUM, 1=AVERAGE, 2=COUNT) Critical when working with filtered data — regular SUM counts hidden rows, SUBTOTAL doesn't. Essential for financial reports with filters.",
    "section": "Ch39 — Mathematical & Statistical Functions"
  },
  {
    "paper": "EXCEL",
    "title": "VLOOKUP (Vertical Lookup)",
    "eq": "=VLOOKUP(lookup_value, table_array, col_index, [range_lookup]) Example: =VLOOKUP(A2, $D$2:$F$100, 3, FALSE) → Find value in A2 in column D of the table, return value from column 3 (column F), exact match (FALSE) Limitations: Only looks RIGHT (cannot look left). col_index breaks if columns are inserted. Use FALSE for exact match always in finance. Slower than INDEX-MATCH on large datasets.",
    "section": "Ch39 — Lookup Functions — Full Reference"
  },
  {
    "paper": "EXCEL",
    "title": "INDEX-MATCH (The Power Combo)",
    "eq": "=INDEX(return_range, MATCH(lookup_value, lookup_range, 0)) Example: =INDEX($F$2:$F$100, MATCH(A2, $D$2:$D$100, 0)) → MATCH finds the row number where A2 appears in column D. INDEX returns the value from column F at that row. Advantages over VLOOKUP: Can look LEFT. Does not break when columns inserted. Faster on large data. More flexible. Industry standard in Big 4 and IB models. Always use this instead of VLOOKUP.",
    "section": "Ch39 — Lookup Functions — Full Reference"
  },
  {
    "paper": "EXCEL",
    "title": "XLOOKUP (Modern Replacement)",
    "eq": "=XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode]) Example: =XLOOKUP(A2, $D$2:$D$100, $F$2:$F$100, \"Not Found\") Available in Excel 365 and Excel 2021+. Combines best of VLOOKUP and INDEX-MATCH. Can look left or right. Built-in error handling (if_not_found). Cleaner syntax. Use XLOOKUP if your Excel version supports it — otherwise use INDEX-MATCH.",
    "section": "Ch39 — Lookup Functions — Full Reference"
  },
  {
    "paper": "EXCEL",
    "title": "MATCH (Standalone)",
    "eq": "=MATCH(lookup_value, lookup_array, [match_type]) Example: =MATCH(\"Revenue\", A1:A20, 0) → returns row number of \"Revenue\" in A1:A20 Returns the POSITION (row or column number) — not the value itself. match_type 0 = exact match. Used inside INDEX-MATCH and for dynamic chart ranges.",
    "section": "Ch39 — Lookup Functions — Full Reference"
  },
  {
    "paper": "EXCEL",
    "title": "OFFSET (Dynamic Ranges)",
    "eq": "=OFFSET(reference, rows, cols, [height], [width]) Example: =OFFSET(A1, 5, 2) → cell that is 5 rows down and 2 columns right of A1 (= C6) Creates dynamic ranges — useful for rolling averages, dynamic chart ranges, expanding datasets. Volatile function (recalculates every time) — use INDEX instead where possible for performance.",
    "section": "Ch39 — Lookup Functions — Full Reference"
  },
  {
    "paper": "EXCEL",
    "title": "IF",
    "eq": "=IF(logical_test, value_if_true, value_if_false) Example: =IF(A1>0, \"Profit\", \"Loss\") Finance use: =IF(Revenue>Target, BonusRate*Salary, 0) Foundation of all conditional logic. Nest IFs for multiple conditions: =IF(A1>100,\"High\",IF(A1>50,\"Medium\",\"Low\")) — but nested IFs get complex fast. Use IFS instead.",
    "section": "Ch39 — Logical & Conditional Functions"
  },
  {
    "paper": "EXCEL",
    "title": "IFS (Multiple Conditions)",
    "eq": "=IFS(condition1, value1, condition2, value2, condition3, value3, ...) Example: =IFS(Score>=90,\"A\", Score>=80,\"B\", Score>=70,\"C\", TRUE,\"F\") Cleaner than nested IFs. Last condition TRUE acts as \"else\". Available Excel 2019+. In older versions, use nested IF or CHOOSE.",
    "section": "Ch39 — Logical & Conditional Functions"
  },
  {
    "paper": "EXCEL",
    "title": "AND / OR / NOT",
    "eq": "=AND(condition1, condition2) → TRUE only if ALL conditions true =OR(condition1, condition2) → TRUE if ANY condition true =NOT(condition) → reverses TRUE/FALSE Example: =IF(AND(Revenue>1000, Margin>20%), \"Star Product\", \"Review\")",
    "section": "Ch39 — Logical & Conditional Functions"
  },
  {
    "paper": "EXCEL",
    "title": "SUMIF / SUMIFS",
    "eq": "=SUMIF(range, criteria, sum_range) — sum where ONE condition met =SUMIFS(sum_range, range1, criteria1, range2, criteria2) — sum where MULTIPLE conditions met Finance example: =SUMIFS(Revenue, Region, \"North\", Product, \"Software\") → Sum all revenue where Region=\"North\" AND Product=\"Software\" Extremely powerful for financial analysis. Used constantly in management reporting, budget vs actual analysis, segment reporting.",
    "section": "Ch39 — Logical & Conditional Functions"
  },
  {
    "paper": "EXCEL",
    "title": "COUNTIF / COUNTIFS",
    "eq": "=COUNTIF(range, criteria) — count where ONE condition met =COUNTIFS(range1, criteria1, range2, criteria2) — count where MULTIPLE conditions met Finance example: =COUNTIFS(Status, \"Overdue\", Amount, \">\"&10000) → Count invoices that are overdue AND above ₹10,000",
    "section": "Ch39 — Logical & Conditional Functions"
  },
  {
    "paper": "EXCEL",
    "title": "AVERAGEIF / AVERAGEIFS",
    "eq": "=AVERAGEIF(range, criteria, average_range) =AVERAGEIFS(average_range, range1, criteria1, range2, criteria2) Finance example: =AVERAGEIF(Region, \"South\", DaysToCollect) → Average debtor days for Southern region only",
    "section": "Ch39 — Logical & Conditional Functions"
  },
  {
    "paper": "EXCEL",
    "title": "IFERROR / IFNA",
    "eq": "=IFERROR(formula, value_if_error) — catch ANY error =IFNA(formula, value_if_na) — catch only #N/A errors Example: =IFERROR(VLOOKUP(A1,Table,2,FALSE), \"Not Found\") Essential in financial models — prevents ugly #REF!, #N/A, #DIV/0! errors from showing. But be careful: IFERROR can hide genuine formula errors. Only use when errors are expected (e.g. no match found).",
    "section": "Ch39 — Logical & Conditional Functions"
  },
  {
    "paper": "EXCEL",
    "title": "TODAY / NOW",
    "eq": "=TODAY() — current date (updates every day) =NOW() — current date and time Use TODAY() in dashboard headers, age calculations. WARNING: volatile — recalculates on every change. Freeze with Ctrl+; if you want static date.",
    "section": "Ch39 — Date Functions"
  },
  {
    "paper": "EXCEL",
    "title": "DATE / YEAR / MONTH / DAY",
    "eq": "=DATE(2025,12,31) — create a date from year/month/day =YEAR(A1) / =MONTH(A1) / =DAY(A1) — extract components =DATE(YEAR(A1),MONTH(A1)+1,0) — last day of current month (very useful for financial period end dates)",
    "section": "Ch39 — Date Functions"
  },
  {
    "paper": "EXCEL",
    "title": "DATEDIF / DAYS / NETWORKDAYS",
    "eq": "=DATEDIF(start_date, end_date, \"Y\") — years between dates (\"M\"=months, \"D\"=days) =DAYS(end_date, start_date) — number of days between dates =NETWORKDAYS(start, end, [holidays]) — working days excluding weekends and holidays NETWORKDAYS critical for payment terms, project deadlines, days outstanding calculations.",
    "section": "Ch39 — Date Functions"
  },
  {
    "paper": "EXCEL",
    "title": "EOMONTH",
    "eq": "=EOMONTH(start_date, months) — last day of month, n months away =EOMONTH(A1, 0) — last day of same month as A1 =EOMONTH(A1, 1) — last day of next month Invaluable for financial model date structures — building monthly/quarterly timelines automatically.",
    "section": "Ch39 — Date Functions"
  },
  {
    "paper": "EXCEL",
    "title": "NPV (Net Present Value)",
    "eq": "=NPV(rate, value1, value2, ...) + initial_investment CRITICAL: Excel's NPV assumes cash flows start at END of period 1 (not period 0). Always add period 0 investment separately. Example: Initial investment ₹100Cr (now), cash flows ₹30Cr, ₹40Cr, ₹50Cr, ₹60Cr, discount rate 12%: =NPV(12%, 30, 40, 50, 60) + (-100) → correct NPV NOT: =NPV(12%, -100, 30, 40, 50, 60) → WRONG — this discounts the initial investment which should not be discounted. If NPV > 0 → Accept project. If NPV < 0 → Reject. Links directly to Chapter 22 (Corporate Finance) and Chapter 33 (Valuation).",
    "section": "Ch39 — Financial Functions — Full Reference with Finance Context"
  },
  {
    "paper": "EXCEL",
    "title": "XNPV (NPV with Actual Dates)",
    "eq": "=XNPV(rate, values, dates) Example: =XNPV(12%, B2:B6, A2:A6) where A2:A6 are actual dates and B2:B6 are cash flows More accurate than NPV when cash flows don't occur at exactly equal intervals. Use XNPV in real financial models — NPV assumes equal periods.",
    "section": "Ch39 — Financial Functions — Full Reference with Finance Context"
  },
  {
    "paper": "EXCEL",
    "title": "IRR (Internal Rate of Return)",
    "eq": "=IRR(values, [guess]) Example: =IRR({-100, 30, 40, 50, 60}) → rate at which NPV = 0 Initial investment must be NEGATIVE. Values must include at least one negative (outflow) and one positive (inflow). If IRR > cost of capital (hurdle rate) → Accept. Multiple IRRs possible if cash flows change sign more than once — be careful.",
    "section": "Ch39 — Financial Functions — Full Reference with Finance Context"
  },
  {
    "paper": "EXCEL",
    "title": "XIRR (IRR with Actual Dates)",
    "eq": "=XIRR(values, dates, [guess]) Example: =XIRR(B2:B6, A2:A6) — IRR using actual payment dates Use XIRR instead of IRR in real models — more accurate when cash flows don't occur at exactly annual intervals. Standard in PE/VC investment returns modelling.",
    "section": "Ch39 — Financial Functions — Full Reference with Finance Context"
  },
  {
    "paper": "EXCEL",
    "title": "PV (Present Value)",
    "eq": "=PV(rate, nper, pmt, [fv], [type]) Example: PV of ₹10,000 received annually for 5 years at 10%: =PV(10%, 5, -10000) → ₹37,908 rate = periodic rate. nper = number of periods. pmt = periodic payment (negative = outflow). fv = future value. type = 0 (end of period, default) or 1 (beginning of period).",
    "section": "Ch39 — Financial Functions — Full Reference with Finance Context"
  },
  {
    "paper": "EXCEL",
    "title": "FV (Future Value)",
    "eq": "=FV(rate, nper, pmt, [pv], [type]) Example: FV of ₹10,000 invested annually for 10 years at 8%: =FV(8%, 10, -10000) → ₹1,44,866 FV of lump sum: =FV(8%, 10, 0, -100000) → FV of ₹1L invested today for 10 years at 8%. Useful for retirement planning, savings projections.",
    "section": "Ch39 — Financial Functions — Full Reference with Finance Context"
  },
  {
    "paper": "EXCEL",
    "title": "PMT (Loan Payment)",
    "eq": "=PMT(rate, nper, pv, [fv], [type]) Example: Monthly EMI for ₹50L home loan at 8.5% for 20 years: =PMT(8.5%/12, 20*12, -5000000) → ₹43,391 per month rate must match period — for monthly payments, divide annual rate by 12. nper = total number of payments (years × 12 for monthly). Used for loan amortisation schedules, lease payment calculations.",
    "section": "Ch39 — Financial Functions — Full Reference with Finance Context"
  },
  {
    "paper": "EXCEL",
    "title": "RATE / NPER",
    "eq": "=RATE(nper, pmt, pv) — find the interest rate given payments =NPER(rate, pmt, pv) — find number of periods to repay a loan Example: =RATE(60, -5000, 200000) → monthly rate on loan of ₹2L, 60 monthly payments of ₹5,000 =NPER(8%/12, -10000, 500000) → months to repay ₹5L at 8% with ₹10,000/month payments",
    "section": "Ch39 — Financial Functions — Full Reference with Finance Context"
  },
  {
    "paper": "POWER BI",
    "title": "Basic Aggregations",
    "eq": "Total Revenue = SUM(Sales[Revenue]) Total Cost = SUM(Sales[Cost]) Gross Profit = [Total Revenue] - [Total Cost] GP Margin % = DIVIDE([Gross Profit], [Total Revenue], 0) Always use DIVIDE() instead of / to handle division by zero gracefully.",
    "section": "Ch40 — Essential DAX Measures for Finance"
  },
  {
    "paper": "POWER BI",
    "title": "Year-over-Year Comparison",
    "eq": "Revenue LY = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR(Dates[Date])) YoY Growth = [Total Revenue] - [Revenue LY] YoY Growth % = DIVIDE([YoY Growth], [Revenue LY], 0) SAMEPERIODLASTYEAR is a time intelligence function — requires a proper Date table marked as Date Table.",
    "section": "Ch40 — Essential DAX Measures for Finance"
  },
  {
    "paper": "POWER BI",
    "title": "Year-to-Date (YTD)",
    "eq": "Revenue YTD = CALCULATE([Total Revenue], DATESYTD(Dates[Date])) Revenue YTD LY = CALCULATE([Total Revenue], DATESYTD(SAMEPERIODLASTYEAR(Dates[Date]))) For financial year YTD (not calendar year): DATESYTD(Dates[Date], \"31-03\") — ends March 31 (India financial year).",
    "section": "Ch40 — Essential DAX Measures for Finance"
  },
  {
    "paper": "POWER BI",
    "title": "Budget Variance",
    "eq": "Budget = SUM(Budget[BudgetAmount]) Variance = [Total Revenue] - [Budget] Variance % = DIVIDE([Variance], [Budget], 0) Variance Flag = IF([Variance %] < -0.05, \"⚠️ Below Budget\", \"✅ On Track\")",
    "section": "Ch40 — Essential DAX Measures for Finance"
  },
  {
    "paper": "POWER BI",
    "title": "CALCULATE — The Most Important DAX Function",
    "eq": "CALCULATE(expression, filter1, filter2, ...) Revenue North = CALCULATE([Total Revenue], Region[Region] = \"North\") Revenue excl Returns = CALCULATE([Total Revenue], Sales[Type] <> \"Return\") Revenue Last Month = CALCULATE([Total Revenue], PREVIOUSMONTH(Dates[Date])) CALCULATE modifies the filter context — it's the engine behind 80% of all advanced DAX. Master this and you can build almost any measure.",
    "section": "Ch40 — Essential DAX Measures for Finance"
  },
  {
    "paper": "POWER BI",
    "title": "ALL — Remove Filters",
    "eq": "% of Total Revenue = DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALL(Sales))) ALL() removes ALL filters from a table — giving the grand total regardless of slicers. DIVIDE([Revenue], [Revenue with ALL]) gives % contribution of each row to the total. Essential for % share calculations.",
    "section": "Ch40 — Essential DAX Measures for Finance"
  },
  {
    "paper": "POWER BI",
    "title": "RANKX — Ranking",
    "eq": "Revenue Rank = RANKX(ALL(Products[Product]), [Total Revenue],,DESC) Ranks each product by revenue across the entire product table (ALL removes filter). Use to show Top 10 products, rank sales reps by performance, rank cost centres by spend.",
    "section": "Ch40 — Essential DAX Measures for Finance"
  },
  {
    "paper": "POWER BI",
    "title": "SWITCH — Multiple Conditions",
    "eq": "Performance Rating = SWITCH(TRUE(), [Variance %] >= 0.1, \"🟢 Excellent\", [Variance %] >= 0, \"🟡 On Target\", [Variance %] >= -0.1, \"🟠 Watch\", \"🔴 Critical\") Cleaner than nested IF statements. SWITCH(TRUE(),...) evaluates each condition in order and returns the first TRUE result.",
    "section": "Ch40 — Essential DAX Measures for Finance"
  },
  {
    "paper": "POWER BI",
    "title": "Moving Average",
    "eq": "3-Month Moving Avg Revenue = CALCULATE([Total Revenue], DATESINPERIOD(Dates[Date], LASTDATE(Dates[Date]), -3, MONTH)) / 3 DATESINPERIOD defines a rolling window of 3 months ending at the current date. Dividing by 3 gives the average. Use for smoothing volatile monthly data in dashboards.",
    "section": "Ch40 — Essential DAX Measures for Finance"
  },
  {
    "paper": "POWER BI",
    "title": "Total Revenue",
    "eq": "= SUM(Sales[Revenue])",
    "section": "Ch40 — Essential DAX Quick Reference"
  },
  {
    "paper": "POWER BI",
    "title": "GP Margin %",
    "eq": "= DIVIDE([Gross Profit], [Total Revenue], 0)",
    "section": "Ch40 — Essential DAX Quick Reference"
  },
  {
    "paper": "POWER BI",
    "title": "Revenue Last Year",
    "eq": "= CALCULATE([Total Revenue], SAMEPERIODLASTYEAR(Dates[Date]))",
    "section": "Ch40 — Essential DAX Quick Reference"
  },
  {
    "paper": "POWER BI",
    "title": "Revenue YTD",
    "eq": "= CALCULATE([Total Revenue], DATESYTD(Dates[Date], \"31-03\"))",
    "section": "Ch40 — Essential DAX Quick Reference"
  },
  {
    "paper": "POWER BI",
    "title": "Budget Variance %",
    "eq": "= DIVIDE([Total Revenue] - [Budget], [Budget], 0)",
    "section": "Ch40 — Essential DAX Quick Reference"
  },
  {
    "paper": "POWER BI",
    "title": "% of Total",
    "eq": "= DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALL(Sales)), 0)",
    "section": "Ch40 — Essential DAX Quick Reference"
  },
  {
    "paper": "POWER BI",
    "title": "Revenue Rank",
    "eq": "= RANKX(ALL(Products[Product]), [Total Revenue],, DESC)",
    "section": "Ch40 — Essential DAX Quick Reference"
  },
  {
    "paper": "POWER BI",
    "title": "3M Moving Average",
    "eq": "= CALCULATE([Total Revenue], DATESINPERIOD(Dates[Date], LASTDATE(Dates[Date]), -3, MONTH)) / 3",
    "section": "Ch40 — Essential DAX Quick Reference"
  },
  {
    "paper": "POWER BI",
    "title": "Revenue Filtered",
    "eq": "= CALCULATE([Total Revenue], Region[Region] = \"North\")",
    "section": "Ch40 — Essential DAX Quick Reference"
  },
  {
    "paper": "POWER BI",
    "title": "Status Flag",
    "eq": "= IF([Variance %] >= 0, \"✅ On Track\", \"⚠️ Below Target\")",
    "section": "Ch40 — Essential DAX Quick Reference"
  },
  {
    "paper": "DATA",
    "title": "SELECT — Retrieve Data",
    "eq": "SELECT Revenue, Cost, Region, Month FROM Sales WHERE Year = 2024 AND Region = 'North' ORDER BY Revenue DESC; The most fundamental SQL statement. SELECT what columns, FROM which table, WHERE conditions, ORDER BY for sorting. Like a filtered, sorted PivotTable — but running directly on the database.",
    "section": "Ch41 — Core SQL Commands — Finance Reference"
  },
  {
    "paper": "DATA",
    "title": "GROUP BY + Aggregate Functions",
    "eq": "SELECT Region, SUM(Revenue) AS Total_Revenue, AVG(Margin) AS Avg_Margin, COUNT(*) AS Transaction_Count FROM Sales WHERE Year = 2024 GROUP BY Region HAVING SUM(Revenue) > 1000000 ORDER BY Total_Revenue DESC; GROUP BY aggregates rows — like a PivotTable. SUM, AVG, COUNT, MIN, MAX are aggregate functions. HAVING filters AFTER grouping (WHERE filters before). Essential for financial summaries by dimension.",
    "section": "Ch41 — Core SQL Commands — Finance Reference"
  },
  {
    "paper": "DATA",
    "title": "JOIN — Combine Tables",
    "eq": "SELECT s.Invoice_No, s.Revenue, c.Customer_Name, c.Region, p.Product_Name FROM Sales s INNER JOIN Customers c ON s.Customer_ID = c.Customer_ID INNER JOIN Products p ON s.Product_ID = p.Product_ID WHERE s.Date >= '2024-01-01'; JOIN combines data from multiple tables using a matching key — like VLOOKUP but for entire tables simultaneously. INNER JOIN: only matching rows. LEFT JOIN: all rows from left table + matches from right. This is the SQL equivalent of building a data model.",
    "section": "Ch41 — Core SQL Commands — Finance Reference"
  },
  {
    "paper": "DATA",
    "title": "CASE WHEN — Conditional Logic",
    "eq": "SELECT Invoice_No, Amount, CASE WHEN Days_Overdue = 0 THEN 'Current' WHEN Days_Overdue WHEN Days_Overdue ELSE '60+ Days' END AS Aging_Bucket FROM Receivables; CASE WHEN is SQL's IF statement — creates conditional categories. Essential for aged receivables analysis, risk banding, performance rating. Same logic as Excel's IFS function.",
    "section": "Ch41 — Core SQL Commands — Finance Reference"
  },
  {
    "paper": "DATA",
    "title": "Window Functions — Running Totals & Rankings",
    "eq": "SELECT Month, Revenue, SUM(Revenue) OVER (ORDER BY Month) AS Running_Total, LAG(Revenue, 1) OVER (ORDER BY Month) AS Prev_Month_Revenue, Revenue - LAG(Revenue,1) OVER (ORDER BY Month) AS MoM_Change, RANK() OVER (PARTITION BY Region ORDER BY Revenue DESC) AS Revenue_Rank FROM Sales; Window functions perform calculations across rows related to current row — without collapsing to summary. Running totals, month-over-month changes, ranking within partitions — all in one query. OVER() defines the window. Essential for time-series financial analysis in SQL.",
    "section": "Ch41 — Core SQL Commands — Finance Reference"
  },
  {
    "paper": "DATA",
    "title": "CTEs — Readable Complex Queries",
    "eq": "WITH Monthly_Revenue AS ( SELECT Month, SUM(Revenue) AS Revenue FROM Sales GROUP BY Month ), Revenue_with_Growth AS ( SELECT Month, Revenue, LAG(Revenue) OVER (ORDER BY Month) AS Prev_Revenue FROM Monthly_Revenue ) SELECT Month, Revenue, ROUND((Revenue - Prev_Revenue) / Prev_Revenue * 100, 2) AS Growth_Pct FROM Revenue_with_Growth; CTEs (Common Table Expressions) create temporary named result sets — like named ranges in Excel. Break complex queries into readable, manageable steps. Much cleaner than deeply nested subqueries.",
    "section": "Ch41 — Core SQL Commands — Finance Reference"
  },
  {
    "paper": "DATA",
    "title": "Descriptive Statistics",
    "eq": "Mean (Average): Sum ÷ Count — central tendency Median: Middle value — better than mean for skewed data (e.g. income distribution) Standard Deviation: Average distance from mean — measures spread/volatility Variance: Standard Deviation² — used in portfolio theory Skewness: Asymmetry of distribution — positive skew (tail right), negative skew (tail left) Finance use: Mean and StDev of returns for investment analysis. Median for customer spend (not mean — one large customer skews mean dramatically).",
    "section": "Ch41 — Key Statistical Concepts for Finance"
  },
  {
    "paper": "DATA",
    "title": "Correlation",
    "eq": "Correlation coefficient (r): -1 to +1 +1 = perfect positive correlation (both move together) 0 = no linear relationship -1 = perfect negative correlation (one goes up, other goes down) Finance uses: Portfolio diversification (combine negatively correlated assets). Regression (identify key revenue drivers). Fraud detection (transactions that don't correlate with normal patterns). WARNING: Correlation ≠ Causation. Always ask WHY two things correlate before concluding one causes the other.",
    "section": "Ch41 — Key Statistical Concepts for Finance"
  },
  {
    "paper": "DATA",
    "title": "Linear Regression",
    "eq": "Y = a + bX (+ error) Y = dependent variable (what we want to predict) X = independent variable (the driver/predictor) b = slope (how much Y changes for one unit increase in X) a = intercept (value of Y when X = 0) R² = goodness of fit (0–1, higher = model explains more variance) Finance uses: Revenue forecasting (Y=Revenue, X=GDP growth or advertising spend). Cost modelling (Y=total cost, X=production volume). Risk modelling (Y=default probability, X=leverage ratio). In Excel: Data → Data Analysis → Regression. In Python: sklearn LinearRegression.",
    "section": "Ch41 — Key Statistical Concepts for Finance"
  },
  {
    "paper": "DATA",
    "title": "Time Series Analysis",
    "eq": "Components of time series: Trend: Long-term direction (revenue growing at 10% CAGR) Seasonality: Regular pattern (retail revenue peaks in December every year) Cyclicality: Longer irregular cycles (economic cycle, 5-10 years) Irregular/Noise: Random variation not explained by above Finance use: Isolate seasonality to understand true underlying trend. Compare this December to last December (same seasonal position) rather than to November. Moving averages smooth out noise to reveal trend.",
    "section": "Ch41 — Key Statistical Concepts for Finance"
  },
  {
    "paper": "DATA",
    "title": "Probability & Expected Value",
    "eq": "Expected Value = Σ (Probability × Outcome) Example: New product launch Success (40% probability) → ₹200Cr NPV Failure (60% probability) → -₹50Cr NPV Expected Value = (0.4 × 200) + (0.6 × -50) = ₹50Cr Foundation of scenario analysis, risk management, and decision trees. ACCA AFM: expected values in project appraisal questions. Risk management: expected loss = Probability of Default × Loss Given Default (credit risk).",
    "section": "Ch41 — Key Statistical Concepts for Finance"
  }
];
