/* Practice Question Bank - extracted from Chapter 50.
   Generated by tools/extract_data.py - do not edit by hand. */
const QUIZ = [
  {
    "paper": "BT (Business & Technology) — Applied Knowledge",
    "code": "BT",
    "q": "Which analysis tool examines Political, Economic, Social, Technological, Environmental and Legal factors?",
    "opts": [
      "A) SWOT Analysis",
      "B) PESTEL Analysis",
      "C) Porter's Five Forces",
      "D) BCG Matrix"
    ],
    "ans": 1,
    "exp": "PESTEL is specifically the macro-environmental scanning tool covering these six factors."
  },
  {
    "paper": "BT (Business & Technology) — Applied Knowledge",
    "code": "BT",
    "q": "A shop window display of goods with price tags is legally classified as:",
    "opts": [
      "A) A binding offer",
      "B) An invitation to treat",
      "C) A unilateral contract",
      "D) A counter-offer"
    ],
    "ans": 1,
    "exp": "Displayed goods invite customers to make an offer at the till — the shop is not obligated to sell at the displayed price."
  },
  {
    "paper": "BT (Business & Technology) — Applied Knowledge",
    "code": "BT",
    "q": "Which of the following is NOT one of the 5 core business functions typically covered in BT?",
    "opts": [
      "A) Operations",
      "B) Marketing",
      "C) Finance",
      "D) Astrology"
    ],
    "ans": 3,
    "exp": "The core functions are Operations, Marketing, HR, Finance, and IT/Information Systems."
  },
  {
    "paper": "BT (Business & Technology) — Applied Knowledge",
    "code": "BT",
    "q": "A phishing attack primarily exploits which vulnerability?",
    "opts": [
      "A) Weak encryption algorithms",
      "B) Human trust and judgement",
      "C) Hardware failure",
      "D) Network bandwidth limits"
    ],
    "ans": 1,
    "exp": "Phishing is a social engineering technique — it tricks people into revealing information rather than exploiting a technical flaw."
  },
  {
    "paper": "MA (Management Accounting) — Applied Knowledge",
    "code": "MA",
    "q": "Which of these costs is classified as variable?",
    "opts": [
      "A) Factory rent",
      "B) Straight-line depreciation",
      "C) Direct material",
      "D) Factory manager's salary"
    ],
    "ans": 2,
    "exp": "Direct material cost moves in direct proportion to production volume; the other three are typically fixed."
  },
  {
    "paper": "MA (Management Accounting) — Applied Knowledge",
    "code": "MA",
    "q": "A company has selling price ₹80/unit, variable cost ₹50/unit, and fixed costs of ₹1,50,000. What is the break-even point in units?",
    "opts": [
      "A) 3,000 units",
      "B) 5,000 units",
      "C) 1,875 units",
      "D) 2,500 units"
    ],
    "ans": 1,
    "exp": "Contribution/unit = ₹80−₹50 = ₹30. BEP = ₹1,50,000 ÷ ₹30 = 5,000 units."
  },
  {
    "paper": "MA (Management Accounting) — Applied Knowledge",
    "code": "MA",
    "q": "Material Price Variance is calculated as:",
    "opts": [
      "A) (Standard Qty − Actual Qty) × Standard Price",
      "B) (Standard Price − Actual Price) × Actual Quantity",
      "C) (Actual Price − Standard Price) × Standard Quantity",
      "D) (Standard Price − Actual Price) × Standard Quantity"
    ],
    "ans": 1,
    "exp": "Price variance isolates the price effect — it's always calculated on the ACTUAL quantity purchased/used."
  },
  {
    "paper": "MA (Management Accounting) — Applied Knowledge",
    "code": "MA",
    "q": "If Margin of Safety increases, this means:",
    "opts": [
      "A) The business is closer to break-even and riskier",
      "B) The business has more cushion above break-even — lower risk",
      "C) Fixed costs have increased",
      "D) Contribution per unit has decreased"
    ],
    "ans": 1,
    "exp": "A larger Margin of Safety (Actual Sales − Break-Even Sales) means more room before the business starts making a loss."
  },
  {
    "paper": "FA (Financial Accounting) — Applied Knowledge",
    "code": "FA",
    "q": "Purchasing a delivery van on credit affects the accounting equation by:",
    "opts": [
      "A) Increasing Assets and Increasing Equity",
      "B) Increasing Assets and Increasing Liabilities",
      "C) Decreasing Assets and Increasing Liabilities",
      "D) No effect — it's an off-balance-sheet transaction"
    ],
    "ans": 1,
    "exp": "The van (asset) increases, and since it's on credit, a payable (liability) increases by the same amount — the equation stays balanced."
  },
  {
    "paper": "FA (Financial Accounting) — Applied Knowledge",
    "code": "FA",
    "q": "A machine costs ₹1,20,000, has an estimated residual value of ₹12,000, and a useful life of 6 years. Annual straight-line depreciation is:",
    "opts": [
      "A) ₹20,000",
      "B) ₹18,000",
      "C) ₹22,000",
      "D) ₹16,000"
    ],
    "ans": 1,
    "exp": "(₹1,20,000 − ₹12,000) ÷ 6 = ₹18,000 per year."
  },
  {
    "paper": "FA (Financial Accounting) — Applied Knowledge",
    "code": "FA",
    "q": "Under IAS 2, inventory is valued at:",
    "opts": [
      "A) Historical cost only",
      "B) Net Realisable Value only",
      "C) Lower of Cost and Net Realisable Value",
      "D) Fair value through profit or loss"
    ],
    "ans": 2,
    "exp": "IAS 2 requires the LOWER of cost and NRV — this prevents overstating inventory when its value has fallen."
  },
  {
    "paper": "FA (Financial Accounting) — Applied Knowledge",
    "code": "FA",
    "q": "In a trial balance, if total debits do not equal total credits, this most likely indicates:",
    "opts": [
      "A) A compensating error",
      "B) A one-sided entry or arithmetic error",
      "C) An error of principle",
      "D) An error of omission"
    ],
    "ans": 1,
    "exp": "Errors of principle, omission, and compensating errors do NOT cause a trial balance imbalance since both sides are still equal (just wrong) — only a one-sided or arithmetic error breaks the balance."
  },
  {
    "paper": "LW (Corporate & Business Law) — Applied Skills",
    "code": "LW",
    "q": "A counter-offer (changing any term of the original offer) has the legal effect of:",
    "opts": [
      "A) Automatically becoming a binding contract",
      "B) Destroying the original offer and becoming a new offer",
      "C) Being ignored — the original offer still stands",
      "D) Creating two simultaneous valid offers"
    ],
    "ans": 1,
    "exp": "A counter-offer kills the original offer — the offeror is no longer bound by their initial terms."
  },
  {
    "paper": "LW (Corporate & Business Law) — Applied Skills",
    "code": "LW",
    "q": "Consideration in a contract must be:",
    "opts": [
      "A) Adequate (i.e. represent fair market value)",
      "B) Sufficient, but need not be adequate",
      "C) In the form of money only",
      "D) Provided before the promise was made"
    ],
    "ans": 1,
    "exp": "Courts require consideration to have SOME value (sufficiency) but won't assess whether it's a fair/equal exchange (adequacy)."
  },
  {
    "paper": "LW (Corporate & Business Law) — Applied Skills",
    "code": "LW",
    "q": "Which remedy is discretionary and typically granted only when damages would be an inadequate remedy (e.g. sale of unique goods)?",
    "opts": [
      "A) Damages",
      "B) Specific Performance",
      "C) Rescission",
      "D) Liquidated Damages"
    ],
    "ans": 1,
    "exp": "Specific Performance is an equitable, discretionary remedy — courts grant it sparingly, mainly where money alone can't fairly compensate the innocent party."
  },
  {
    "paper": "LW (Corporate & Business Law) — Applied Skills",
    "code": "LW",
    "q": "Social or domestic agreements between family members are presumed to:",
    "opts": [
      "A) Always be legally binding",
      "B) Never have intention to create legal relations, though this can be rebutted",
      "C) Require written form to be valid",
      "D) Automatically require consideration of at least ₹1"
    ],
    "ans": 1,
    "exp": "The law presumes no intention to be legally bound in social/domestic settings — but this presumption CAN be rebutted with clear evidence otherwise."
  },
  {
    "paper": "PM (Performance Management) — Applied Skills",
    "code": "PM",
    "q": "A Throughput Accounting Ratio (TPAR) greater than 1 indicates:",
    "opts": [
      "A) The product destroys value and should be dropped",
      "B) The product is profitable to produce at the bottleneck",
      "C) Fixed costs exceed variable costs",
      "D) The learning curve has ended"
    ],
    "ans": 1,
    "exp": "TPAR > 1 means throughput per bottleneck minute exceeds factory cost per bottleneck minute — the product generates value faster than it costs."
  },
  {
    "paper": "PM (Performance Management) — Applied Skills",
    "code": "PM",
    "q": "The learning curve effect assumes that as cumulative output doubles, the cumulative average time per unit:",
    "opts": [
      "A) Increases by a fixed percentage",
      "B) Falls by a constant percentage",
      "C) Remains unchanged",
      "D) Falls to zero"
    ],
    "ans": 1,
    "exp": "This is the defining property of a learning curve — e.g. an 80% curve means cumulative average time falls to 80% of its previous level each time output doubles."
  },
  {
    "paper": "PM (Performance Management) — Applied Skills",
    "code": "PM",
    "q": "In mix and yield variance analysis, the Mix Variance isolates the effect of:",
    "opts": [
      "A) Using a different total quantity of input than budgeted",
      "B) Using a different PROPORTION of materials than the standard mix",
      "C) A change in the selling price",
      "D) A change in labour efficiency"
    ],
    "ans": 1,
    "exp": "Mix variance measures the cost impact of blending materials in a different ratio than standard — separate from the total quantity (yield) effect."
  },
  {
    "paper": "TX (Taxation) — Applied Skills",
    "code": "TX",
    "q": "Under Section 115BAA, a domestic company forgoing exemptions/deductions is taxed at a base rate of:",
    "opts": [
      "A) 15%",
      "B) 22%",
      "C) 25%",
      "D) 30%"
    ],
    "ans": 1,
    "exp": "Section 115BAA offers a concessional 22% base rate (before surcharge and cess) for domestic companies that opt out of specified exemptions."
  },
  {
    "paper": "TX (Taxation) — Applied Skills",
    "code": "TX",
    "q": "The Health & Education Cess applied on corporate tax (plus surcharge) in India is:",
    "opts": [
      "A) 2%",
      "B) 3%",
      "C) 4%",
      "D) 5%"
    ],
    "ans": 2,
    "exp": "The cess is levied at 4% on the total of tax plus applicable surcharge."
  },
  {
    "paper": "TX (Taxation) — Applied Skills",
    "code": "TX",
    "q": "Which of these is a DIRECT tax in the Indian tax system?",
    "opts": [
      "A) GST",
      "B) Customs Duty",
      "C) Corporate Income Tax",
      "D) Excise Duty"
    ],
    "ans": 2,
    "exp": "Direct taxes (income tax, corporate tax) are levied directly on income/profit; GST, customs, and excise are indirect taxes on transactions/goods."
  },
  {
    "paper": "FR (Financial Reporting) — Applied Skills",
    "code": "FR",
    "q": "Under IFRS 16, how does a lessee generally account for a lease (with limited exceptions)?",
    "opts": [
      "A) Off-balance-sheet, expensed as incurred",
      "B) Recognised on-balance-sheet as a Right-of-Use asset and a Lease Liability",
      "C) As a contingent liability only",
      "D) Only disclosed in the notes"
    ],
    "ans": 1,
    "exp": "IFRS 16 removed the old operating/finance lease distinction for lessees — almost all leases now go on-balance-sheet."
  },
  {
    "paper": "FR (Financial Reporting) — Applied Skills",
    "code": "FR",
    "q": "The 5-step revenue recognition model under IFRS 15 begins with:",
    "opts": [
      "A) Recognising revenue when performance obligations are satisfied",
      "B) Identifying the contract with a customer",
      "C) Determining the transaction price",
      "D) Allocating the transaction price"
    ],
    "ans": 1,
    "exp": "Step 1 is identifying the contract — the other steps (price determination, allocation, obligation identification, recognition) follow in sequence."
  },
  {
    "paper": "FR (Financial Reporting) — Applied Skills",
    "code": "FR",
    "q": "Diluted EPS differs from Basic EPS because it:",
    "opts": [
      "A) Uses only the current year's profit",
      "B) Adjusts for potentially dilutive instruments like convertible bonds and share options",
      "C) Ignores preference dividends",
      "D) Uses the opening share count only"
    ],
    "ans": 1,
    "exp": "Diluted EPS shows the 'worst case' impact on EPS if all dilutive instruments (options, convertibles) were converted to ordinary shares."
  },
  {
    "paper": "AA (Audit & Assurance) — Applied Skills",
    "code": "AA",
    "q": "Per the Audit Risk Model, Audit Risk equals:",
    "opts": [
      "A) Inherent Risk + Control Risk + Detection Risk",
      "B) Inherent Risk × Control Risk × Detection Risk",
      "C) Inherent Risk − Control Risk",
      "D) Detection Risk ÷ Control Risk"
    ],
    "ans": 1,
    "exp": "The three risk components MULTIPLY together (not add) to give overall Audit Risk."
  },
  {
    "paper": "AA (Audit & Assurance) — Applied Skills",
    "code": "AA",
    "q": "Segregation of duties is a control designed primarily to prevent:",
    "opts": [
      "A) Slow processing of transactions",
      "B) One individual having the ability to both commit and conceal an error or fraud",
      "C) High audit fees",
      "D) Inventory obsolescence"
    ],
    "ans": 1,
    "exp": "Splitting authorisation, custody, and recording functions across different people makes it much harder for any single person to commit AND hide fraud."
  },
  {
    "paper": "AA (Audit & Assurance) — Applied Skills",
    "code": "AA",
    "q": "Which of the following is the strongest form of audit evidence?",
    "opts": [
      "A) Verbal representation from management",
      "B) Auditor's own physical inspection / third-party confirmation",
      "C) Client-prepared internal memo",
      "D) Prior year's unaudited figures"
    ],
    "ans": 1,
    "exp": "Evidence obtained directly by the auditor or from independent third parties is generally more reliable than evidence from the client itself."
  },
  {
    "paper": "FM (Financial Management) — Applied Skills",
    "code": "FM",
    "q": "In the CAPM formula Ke = Rf + β(Rm − Rf), the term (Rm − Rf) represents:",
    "opts": [
      "A) The risk-free rate",
      "B) The Equity Risk Premium",
      "C) The company's Beta",
      "D) The cost of debt"
    ],
    "ans": 1,
    "exp": "(Rm − Rf) is the extra return investors demand for taking on equity market risk over a risk-free investment."
  },
  {
    "paper": "FM (Financial Management) — Applied Skills",
    "code": "FM",
    "q": "Which investment appraisal method is theoretically superior because it directly measures value created in absolute currency terms?",
    "opts": [
      "A) Payback Period",
      "B) Accounting Rate of Return",
      "C) Net Present Value",
      "D) None — they're all equivalent"
    ],
    "ans": 2,
    "exp": "NPV directly measures the increase in shareholder wealth in ₹ terms, discounted for time value of money — the theoretical gold standard."
  },
  {
    "paper": "FM (Financial Management) — Applied Skills",
    "code": "FM",
    "q": "A key limitation of the Payback Period method is that it:",
    "opts": [
      "A) Is too complex to calculate",
      "B) Ignores the time value of money and cash flows after the payback date",
      "C) Cannot be used for capital-intensive projects",
      "D) Always gives the same answer as NPV"
    ],
    "ans": 1,
    "exp": "Payback is simple and liquidity-focused but ignores discounting and anything that happens after the cutoff point — a real weakness for long-term decisions."
  },
  {
    "paper": "SBL (Strategic Business Leader) — Strategic Professional",
    "code": "SBL",
    "q": "A company launching its EXISTING product into a NEW geographic market is pursuing, per the Ansoff Matrix:",
    "opts": [
      "A) Market Penetration",
      "B) Product Development",
      "C) Market Development",
      "D) Diversification"
    ],
    "ans": 2,
    "exp": "Market Development = existing product, new market. (Product Development would be new product, existing market.)"
  },
  {
    "paper": "SBL (Strategic Business Leader) — Strategic Professional",
    "code": "SBL",
    "q": "The 'Agency Problem' in corporate governance refers to:",
    "opts": [
      "A) Employees being paid through recruitment agencies",
      "B) A conflict of interest between managers (agents) and shareholders (principals)",
      "C) The cost of running a marketing agency campaign",
      "D) A dispute between two competing companies"
    ],
    "ans": 1,
    "exp": "Agents (management) may act in their own interest rather than maximising value for principals (shareholders) — the core governance challenge SBL addresses."
  },
  {
    "paper": "SBL (Strategic Business Leader) — Strategic Professional",
    "code": "SBL",
    "q": "Which of Kotter's 8 Steps for change management comes FIRST?",
    "opts": [
      "A) Forming a powerful coalition",
      "B) Creating a sense of urgency",
      "C) Communicating the vision",
      "D) Anchoring changes in culture"
    ],
    "ans": 1,
    "exp": "Kotter's model begins with establishing urgency — without it, people won't feel motivated to support the change effort."
  },
  {
    "paper": "SBR (Strategic Business Reporting) — Strategic Professional",
    "code": "SBR",
    "q": "Under IAS 21, monetary items on the Statement of Financial Position are translated at:",
    "opts": [
      "A) The historical rate at the transaction date",
      "B) The closing (year-end) rate",
      "C) The average rate for the year",
      "D) A rate fixed by the parent company"
    ],
    "ans": 1,
    "exp": "Monetary items (cash, receivables, payables) are retranslated at closing rate each period, since their settlement value changes with exchange rates."
  },
  {
    "paper": "SBR (Strategic Business Reporting) — Strategic Professional",
    "code": "SBR",
    "q": "Statement of Profit or Loss items for a foreign subsidiary are typically translated using:",
    "opts": [
      "A) The closing rate",
      "B) The average rate for the period",
      "C) The opening rate only",
      "D) The parent company's functional currency rate, unadjusted"
    ],
    "ans": 1,
    "exp": "P&L items are translated at the average rate as a practical approximation of the rates prevailing when the transactions actually occurred."
  },
  {
    "paper": "AFM (Advanced Financial Management) — Strategic Professional",
    "code": "AFM",
    "q": "The Adjusted Present Value (APV) method is preferred over a standard WACC-based NPV when:",
    "opts": [
      "A) The project is very small",
      "B) The capital structure changes significantly over the project's life",
      "C) The company has no debt at all",
      "D) Tax rates are zero"
    ],
    "ans": 1,
    "exp": "APV separates the base-case (all-equity) NPV from financing side-effects, making it more robust when gearing changes materially during the project."
  },
  {
    "paper": "AFM (Advanced Financial Management) — Strategic Professional",
    "code": "AFM",
    "q": "EV/EBITDA is generally preferred over P/E for cross-company comparison because it is:",
    "opts": [
      "A) Always a larger number",
      "B) Capital-structure neutral — unaffected by differing debt levels between companies",
      "C) Based only on historical cost accounting",
      "D) Only usable for loss-making companies"
    ],
    "ans": 1,
    "exp": "EV/EBITDA sits above the interest line, so it isn't distorted by differences in companies' financing/capital structure the way P/E (which uses post-interest EPS) can be."
  },
  {
    "paper": "APM (Advanced Performance Management) — Strategic Professional",
    "code": "APM",
    "q": "Residual Income (RI), unlike ROI, has the advantage of:",
    "opts": [
      "A) Being expressed as a simple percentage, easy to compare across divisions of different sizes",
      "B) Encouraging managers to accept any project that exceeds the cost of capital, avoiding ROI's dilution problem",
      "C) Requiring no knowledge of the cost of capital",
      "D) Being unaffected by asset valuation policy"
    ],
    "ans": 1,
    "exp": "ROI can cause a manager to REJECT a project that's good for the company (because it dilutes their average ROI) — RI avoids this by using an absolute ₹ measure against a required return."
  },
  {
    "paper": "APM (Advanced Performance Management) — Strategic Professional",
    "code": "APM",
    "q": "The best transfer pricing method to use when a genuine external market for the product exists is:",
    "opts": [
      "A) Full Cost basis",
      "B) Cost-Plus basis",
      "C) Market Price basis",
      "D) Negotiated price with no reference point"
    ],
    "ans": 2,
    "exp": "Market price gives an objective, externally-verifiable transfer price and avoids internal disputes over cost allocation or margin fairness."
  },
  {
    "paper": "ATX (Advanced Taxation) — Strategic Professional",
    "code": "ATX",
    "q": "The two principal methods of Double Tax Relief are:",
    "opts": [
      "A) Deferral and Deduction",
      "B) Exemption Method and Credit Method",
      "C) Amnesty and Penalty Waiver",
      "D) Withholding and Refund"
    ],
    "ans": 1,
    "exp": "Under the Exemption Method, foreign income is simply excluded from home-country tax; under the Credit Method, foreign tax paid is credited against the home-country tax liability."
  },
  {
    "paper": "AAA (Advanced Audit & Assurance) — Strategic Professional",
    "code": "AAA",
    "q": "An auditor identifies a misstatement that is material but NOT pervasive, and management refuses to correct it. The appropriate opinion is:",
    "opts": [
      "A) Unmodified (Unqualified) Opinion",
      "B) Qualified Opinion (\"except for\")",
      "C) Adverse Opinion",
      "D) Disclaimer of Opinion"
    ],
    "ans": 1,
    "exp": "Material-but-not-pervasive misstatements warrant a Qualified 'except for' opinion — the financial statements are fine EXCEPT for this specific issue."
  },
  {
    "paper": "AAA (Advanced Audit & Assurance) — Strategic Professional",
    "code": "AAA",
    "q": "If a misstatement is BOTH material AND pervasive, the auditor should issue:",
    "opts": [
      "A) A Qualified Opinion",
      "B) An Adverse Opinion",
      "C) An Unmodified Opinion with an Emphasis of Matter",
      "D) No opinion is required"
    ],
    "ans": 1,
    "exp": "When the impact is so significant and widespread that it undermines the financial statements as a whole, an Adverse Opinion states they do NOT present a true and fair view."
  },
  {
    "paper": "AAA (Advanced Audit & Assurance) — Strategic Professional",
    "code": "AAA",
    "q": "If the auditor is unable to obtain sufficient appropriate evidence, and the possible effect is material and pervasive, the auditor issues:",
    "opts": [
      "A) A Qualified Opinion",
      "B) An Adverse Opinion",
      "C) A Disclaimer of Opinion",
      "D) An Unmodified Opinion"
    ],
    "ans": 2,
    "exp": "A Disclaimer means the auditor cannot form an opinion at all, because they simply couldn't gather enough evidence to reach a conclusion."
  }
];
